### ISSUE TITLE
Does "flux()" get the average in- and outbounds right?

### ISSUE THREAD

**Issue by JoergMBeyer** [stefvanbuuren/mice#102]
Dear Stef et al., 

I'd like to report what arguably looks like a conceptual bug in "flux()" to me. The way both the average inbound ("ainb") and the average outbound ("aout") are calculated, doesn't seem entirely sound. 

In both cases, "flux()" first calculates a full matrix of indices from a given set of variables. "Full" meaning here "bivariate _and univariate_ inbound (or outbound) indices -- that is, explicitely including those of all variables with themselves". After that, row-wise means for said matrix are calculated. In consequence, each row-wise average carries the variable's inbound (or outbound) influence with itself. 

IMHO, this should not be considered correct for the following reasons: As we know, a variable can neither impute nor otherwise impact itself. Hence, univariate inbound or outbound measures are not really a thing; any in- or outbound index of a variable _influenced by itself_ should be considered nonsensical. Violating this constraint, like "flux()" currently does, leads to systematically underestimating the row-wise averages under "ainb" and "aout". 

So, in essence, the problem's root is that the algorithm is being mislead to divide each row-wise sum by its full length (with "mean()"), instead of chipping one off to compensate for the bogus univariate index contained in each row. Luckily, fixing this problem is straightforward by first inserting a small inline function into "flux()" 

    .avg <- function(row) sum(row, na.rm = TRUE)/(length(row) - 1)

and then changing the averaged in-/outbound calculations to 

    ainb <- apply(pat$mr/(pat$mr + pat$mm), 1, .avg)
    aout <- apply(pat$rm/(pat$rm + pat$rr), 1, .avg)

(One could of course speed up the averaging part by factoring out the denominator, so that ".avg()" doesn't have to calculate it over and over again. For now I consider that a non-substantial, minor implementation detail.) 

Thoughts? 

-- Jörg

**Comment by stefvanbuuren** [comment]
Dear Jörg, I think your suggestion makes sense. Below is the result of `flux()` in `mice 3.0.0`.

```
> flux(pattern1)
   pobs    influx outflux      ainb  aout  fico
A 1.000 0.0000000       1       NaN 0.125 0.375
B 1.000 0.0000000       1       NaN 0.125 0.375
C 0.625 0.2857143       0 0.6666667 0.000 0.000

> flux(pattern2)
   pobs    influx   outflux      ainb      aout  fico
A 1.000 0.0000000 1.0000000       NaN 0.2916667 0.625
B 0.750 0.1176471 0.4285714 0.3333333 0.1666667 0.500
C 0.375 0.4705882 0.0000000 0.5333333 0.0000000 0.000

> flux(pattern3)
   pobs influx outflux      ainb      aout fico
A 1.000  0.000   1.000       NaN 0.3333333    1
B 0.625  0.375   0.625 0.6666667 0.3333333    1
C 0.375  0.625   0.375 0.6666667 0.3333333    1

> flux(pattern4)
   pobs influx outflux      ainb      aout      fico
A 0.750  0.125   0.500 0.3333333 0.2222222 0.6666667
B 0.625  0.250   0.375 0.4444444 0.2000000 0.6000000
C 0.625  0.375   0.625 0.6666667 0.3333333 0.6000000
```

which has some `NaN` and uses all three columns. After your correction, the output is

```
> flux(pattern1)
   pobs    influx outflux ainb   aout  fico
A 1.000 0.0000000       1    0 0.1875 0.375
B 1.000 0.0000000       1    0 0.1875 0.375
C 0.625 0.2857143       0    1 0.0000 0.000

> flux(pattern2)
   pobs    influx   outflux ainb   aout  fico
A 1.000 0.0000000 1.0000000  0.0 0.4375 0.625
B 0.750 0.1176471 0.4285714  0.5 0.2500 0.500
C 0.375 0.4705882 0.0000000  0.8 0.0000 0.000

> flux(pattern3)
   pobs influx outflux ainb aout fico
A 1.000  0.000   1.000    0  0.5    1
B 0.625  0.375   0.625    1  0.5    1
C 0.375  0.625   0.375    1  0.5    1

> flux(pattern4)
   pobs influx outflux      ainb      aout      fico
A 0.750  0.125   0.500 0.5000000 0.3333333 0.6666667
B 0.625  0.250   0.375 0.6666667 0.3000000 0.6000000
C 0.625  0.375   0.625 1.0000000 0.5000000 0.6000000
```

I agree with you that `ainb` and `aout` are easier to interpret. As a bonus, the `NaN`'s have gone. 

I will incorporate your suggestion into `mice`. Thanks!

**Comment by stefvanbuuren** [comment]
Now in `mice 3.0.11`.
