### ISSUE TITLE
"pool" does not let me choose "method" and does not work for the "gls" object

### ISSUE THREAD

**Issue by itchyshin** [stefvanbuuren/mice#105]
Dear Stef

We did a simulation using mice while ago and came back now to do some more work. And I realise the function "pool" has changed. 

I get following warnings which worked before

> pool   <- summary(pool(models, method = "smallsample"))
Error in pool(models, method = "smallsample") : 
  unused argument (method = "smallsample")

> pool   <- summary(pool(models))
Error: glance doesn't know how to deal with data of class gls

Our simulation actually shows the sammsample method can sometimes be too conservative and the original one works better. Also, the last pool function worked for all objects with vcv. Can the package offer also the older version of pool in this new version of the package.

Many thanks

Shinichi

**Comment by stefvanbuuren** [comment]
I am afraid we can't support the infinite variety of output formats of `R` functions. `mice 3.0.0` relies on `broom` to do the regularization in output formats. 

Related to #106 and #95.

The `smallsample` argument is not needed anymore. `pool()` will always do the Rubin-Barnard adjustment. You can simply remove the `method` argument.

**Comment by itchyshin** [comment]
Hi Stef

Many thanks for your reply. My point is that the original Rubin's method (without the small sample correction of df) works better under some circumstances (we have done some simulations). The Rubin-Barnard adjustment produces CIs too wide (too conservative). 

Can we still get ones without the Rubin-Barnard adjustment using "pool()"?

Thanks

Shinichi

**Comment by stefvanbuuren** [comment]
This is not possible anymore since `mice 3.1.0`. My idea was we should always prefer the Barnard-Rubin adjustment. I am not aware of work that says otherwise.

If want to undo the Barnard-Rubin correction, change the `dfcom` parameter in `pool` to a large number, say 99999.

**Comment by itchyshin** [comment]
Many thanks for your reply. OK I will try what you suggested. 

Here is our paper: 

https://peerj.com/preprints/1216/

We recently extended this simulation to 12 different trees (scenarios) and sometimes the original df does better in terms of the coverage.

**Comment by stefvanbuuren** [comment]
Thanks for sharing. 

Since df(corrected) < df(original), I expect that the confidence interval corresponding to df(corrected) would always be longer, but your Figure 2 suggests the opposite. I cannot really understand how that could be.

**Comment by gerkovink** [comment]
Thanks for sharing your results. I have looked at your paper and it seems to me that the unadjusted degrees of freedom would yield (slight) undercoverage, while the B&R adjustment yields coverages that are confidence valid cf. Neyman's theory: i.e. the interval reaches at least the nominal level. This for both slope and intercept, for N=10 and N=50. To me it seems that your results verify our preference for B&R. 

@stefvanbuuren The interval is indeed longer under B&R. We are looking at 1-coverage.

**Comment by stefvanbuuren** [comment]
@gerkovink Ah yes, of course. So Barnard-Rubin is indeed more conservative, as we expect.

**Comment by stefvanbuuren** [comment]
Agree with Gerko's suggestion, and would in general prefer the Barnard-Rubin correction. I am closing because I do not think we need to reintroduce the `method` argument.

**Comment by itchyshin** [comment]
Thanks, both @gerkovink and @stefvanbuuren 

Our new simulation (which we will put on the preprint soon) shows that both the original and corrected produce consistently "over"-coverage under many situations (in our simulation). So if this is the case, actually the original has better coverage in terms of 5% error.
