### ISSUE TITLE
NaN returned for df after pooling when dfcom is Inf or NULL

### ISSUE THREAD

**Issue by coreybrier** [stefvanbuuren/mice#110]
When pooling, if `dfcom` is `NULL`  it is assigned `Inf`, but `mice:::barnard.rubin` then returns `NaN` (which is called by `pool.fitlist`).
This is due to, for instance, the calculation in the line:
```
dfobs <- (dfcom + 1)/(dfcom + 3) * dfcom * (1 - lambda)
```

I think previous versions of mice used `mice:::mice.df` for this calculation which included the lines:
``` 
if (is.null(dfcom)) {
        dfcom <- 999999
        warning("Large sample assumed.")
    }
````

Is it possible for similar behavior (assuming a large sample size) in `barnard.rubin`, when one runs `pool`?

Thank you!

mice version: 3.0.0

**Comment by stefvanbuuren** [comment]
Thanks. I got similar requests. I have restored the old behaviour that sets `dfcom <- 999999` when it cannot be extracted from the fitted model.

I also added the `dfcom` argument to `pool()` so that you have external control over it.

Related to #105.

Now in `mice 3.1.2`.

**Comment by coreybrier** [comment]
Great, thank you so much!
