### ISSUE TITLE
Using cbind/rbind issues warning

### ISSUE THREAD

**Issue by stephematician** [stefvanbuuren/mice#114]
This warning pops up if the objects passed to `cbind` has more than one class, e.g.

    > cbind(ordered(c(1,2)))
         [,1]
    [1,]    1
    [2,]    2
    Warning message:
    if (attr(list(...)[[1]], "class") == "mids") return(cbind.mids(...)) else return(base::cbind(...)) :
      the condition has length > 1 and only the first element will be used

The warning could be avoided by using `identical("mids", attr(list(...)[[1]], "class"))` here, or alternatively `"mids" %in% attr(list(...)[[1]], "class")` instead of the condition.

There really should be a neater solution than masking the internal generic `cbind` (or `rbind`) with `mice::cbind` and `mice::rbind`, unfortunately I can't quite get my head around the dispatch mechanism.

**Comment by stefvanbuuren** [comment]
Thanks. `mice 3.1.3` fixes this.

I agree with you that there should be a neater solution than overwriting the `base` version. Will open an new issue for this.
