### ISSUE TITLE
mice() post argument

### ISSUE THREAD

**Issue by stephematician** [stefvanbuuren/mice#116]
Looks to me like `length(post)` should be `length(blocks)` rather than `ncol(data)`

    for (h in visitSequence) {
        ...
        if (univ) {
            for (j in b) {
                ...
            
                # optional post-processing
                cmd <- post[j]
                if (cmd != "") {
                    eval(parse(text = cmd))
                    data[where[, j], j] <- imp[[j]][, i]
                }
            }
        }
        ...
    }

**Comment by stefvanbuuren** [comment]
Variable `b` is a vector of variable names in current block, and `j` is just the name of one variable, so I think the current code works as intended. 

Post-processing will only work when the sampler returns classic univariate imputations. Post-processing of multivariate imputations is currently not supported.

**Comment by stephematician** [comment]
Thanks, I think I follow.

My understanding was that mice() requires all columns in the data to have corresponding columns in `predictorMatrix`, that's fair enough (to an extent). But no post-processing is ever performed on variable that isn't somewhere in `block`, so it doesn't make sense to require the `post` argument to have dimension `ncol(data)`?

**Comment by stefvanbuuren** [comment]
The outcome of a post-processing step is a transformed variable, so I would think that there can be ncol(data) of such operations. What would be your alternatieve?

**Comment by stephematician** [comment]
As far as I can tell, only in the loop above is `post` accessed by sampler, and as you say, `b` is a vector of variable names in the current block. If an element exists in `post` for a variable that isn't named in any element of 'blocks`, it is never parsed and evaluated within `sampler()`.

If `post` is meant to be open to all variables in the data (not just those for which a model is specified) then the code above needs to be revised. An order in which the non-imputed yet post-processed variables needs to be established.

Having said that, I find it difficult to imagine a variable that requires post-processing for which no imputation model is specified; I would have thought passive imputation would be the answer for such cases.

**Comment by stefvanbuuren** [comment]
OK thanks. 

As you indicate, the `post` argument is meant for post-processing just after a variable is imputed, while passive imputation is the more natural candidate for transforming a variable without imputation. 

It's true that variables that specify `post` but that are not imputed will not be processed. Perhaps things could be more elegant, but for now I do not consider this a priority.
