### ISSUE TITLE
Error in "mice: Imputing multi-level data" vignette

### ISSUE THREAD

**Issue by michaelwhammer** [stefvanbuuren/mice#120]
In the vignette it states:

```
11. Now impute the popNCR dataset again with mice using imputation method norm for popular, popteach, texp and extrav, but now include class as a predictor for all variables. Call the mids-object imp2.

pred <- ini$pred
pred[, "pupil"] <- 0
imp2 <- mice(popNCR, meth = meth, pred = pred, print = FALSE)
```

Yet the code isn't setting `class` as a predictor for all variables, but is removing `pupil` from being a predictor for all variables.

**Comment by gerkovink** [comment]
The `predictorMatrix` for the initial mice object declares all columns as predictors for all others, which satisfies exercise 11. Deliberately setting column `class` to `1` would not yield a different `predictorMatrix `. Column `pupil` must be set to zero to avoid that the pupil number serves as a predictor, which would effectively result in no residual standard deviation. 

All the best,

Gerko
