### ISSUE TITLE
Mixed-effects Cox model or Shared Frailty model

### ISSUE THREAD

**Issue by Dadadu84** [stefvanbuuren/mice#123]
Hello, 
I'm dealing with some problems after adding a random-effect in the or a frailty factor.

As you can below I computed a mixed-effects Cox proportional hazards regression after multiple imputation by mice. When I tried to pool the 5 components of the mira object (mixed-effects Cox models from each imputation, m=5) I got an error message reporting that the function cannot handle coxme objects ("Error: glance doesn't know how to deal with data of class coxme"). I think the package routine cannot allow for the random component. Is there any way to bypass this problem? Is there a function/process that can work for my purposes?

As you can see below I tried to change the type of model from mixed-effect to shared frailty model, however, I got the following error message: "Error in if (s$used.robust) nn <- c("estimate", "std.error", "robust.se", : argument is of length zero".

To let you understand the problem I attached an Excel spreadsheet reporting example data ("Treat" is the variable referring to the treatment, "Status" and "Time" refer to the outcome occurrence and follow-up, "x1-x5" are the factors and covariates of which the "x4" and "x5" need for multiple imputation, and finally "Centre" is the original centre).

library("readxl")
library("mice")
library("survival")
library("coxme")

Data <- read_excel(path="C:/../DataExample.xlsx", sheet="Foglio1")

mice_plot <- aggr(Data, col=c('navyblue','yellow'), numbers=TRUE, sortVars=TRUE, labels=names(Data), cex.axis=.7, gap=3, ylab=c("Missing data","Pattern"))

Data$Treat <- factor(Data$Treat, labels=c('Treatment1','Treatment2'))
Data$Centre <- factor(Data$Centre, labels=c('1','2','3','4','5','6','7','8','9'))
Data$x1 <- as.numeric(Data$x1)
Data$x2 <- factor(Data$x2, labels=c("No", "Yes"))
Data$x3 <- factor(Data$x3, labels=c("No", "Yes"))
Data$x4 <- as.numeric(Data$x4)
Data$x5 <- factor(Data$x5, labels=c("No", "Yes"))

DataMImp <- mice(Data, m=5)

DataMImpR <- with(data=DataMImp, expr=coxme(formula = Surv(Time, Status) ~ Treat + (1 | Centre) + x1 + x2 + x3 + x4 + x5))
DataMImpR

summary(pool(DataMImpR))

DataMImpR <- with(data=DataMImp, expr=coxph(formula = Surv(Time, Status) ~ Treat + frailty.gaussian(Centre) + x1 + x2 + x3 + x4 + x5))
DataMImpR

summary(pool(DataMImpR))

Thank you.

[DataExample.xlsx](https://github.com/stefvanbuuren/mice/files/2197234/DataExample.xlsx)

**Comment by stefvanbuuren** [comment]
Great that you’re able to progress. Sorry, but I have no time to delve into this any deeper.

**Comment by CaroHaensch** [comment]
I have the same issue, did you use the approach you  proposed above or did you find a better solution?
