### ISSUE TITLE
Post-processing: conditional imputation with continuous variables

### ISSUE THREAD

**Issue by sommenc** [stefvanbuuren/mice#125]
Dear Stef Van Buuren,

I am trying to use some of your code from your book "Flexible Imputation of Missing Data" to my issue of conditional imputation. In your book, it seems you only treat conditional imputation of categorical variables, which permits to create a special category in the post argument to treat the conditional imputation. My question is how should we proceed to treat conditional continuous variables (as is the case with the option conditional of the ice function of STATA)?

In my Data, I have a continuous variable (Vcontinuous) which couln't have any value before a date LimiDate (variable date coded in continuous variable). Vcontinuous is also a predictor variable in imputation. Thus, I would like use Vcontinuous only for date>=LimiDate for imputation. My first idea was to force Vcontinuous to be missing for date < LimiDate by using the following code :

```
init = mice(myData, maxit=0) 
post=init$post
post["Vcontinuous"] <- "imp[[j]][init$data$date[!r[,j]]<LimiDate ,i])<-NA"
imp<-mice(myData)
```
But MICE does not authorize introduction of NA in post-processing.

Do you have any suggestions for dealing with this problem?

I thank you in advance for you help.

Sincerely,

Cécile Sommen

**Comment by stefvanbuuren** [comment]
Example is not reproducible. Can you define a simple `myData` data frame?

**Comment by stefvanbuuren** [comment]
Does changing 

    post["Vcontinuous"] <- "imp[[j]][init$data$date[!r[,j]]<LimiDate ,i] <- 0"

do what you want?

**Comment by sommenc** [comment]
Unfortunately this solution does not solve my problem because `0 `is a value that can take `Vcontinuous`

**Comment by stefvanbuuren** [comment]
My idea was that setting the value `Vcontinuous = 0`would effectively eliminate it from the expected values calculation for cases with `data < 2005`.

Another alternative is to spit the data into two parts, and specify different a predictor matrix in each. You can combine the `mids` objects by `rbind`.

**Comment by stefvanbuuren** [comment]
This topic is more about modelling and less about software, so I am closing it.

**Comment by vildemaa** [comment]
Hi. I am facing the same problem as described here. 

I want to keep missing values (NAs) in the variable AgeFirstChild (giving the participants age when having her first child) if the participant does not have any children (i.e. if NChild == 0).

I define the following post-processing: 
post["AgeFirstChild"] <- "imp[[j]][data$NChild[!r[,j]] %in% 0, i] <- NA" 

And as described in this thead, I get NA in all variables predicted by the conditional variable NChild with NChild == 0. 

Have anyone found a solution to the problem? :)
