### ISSUE TITLE
Test on D1() fails on some systems

### ISSUE THREAD

**Issue by stefvanbuuren** [stefvanbuuren/mice#128]
The following statement in `test/testthat/test-D1.R` fails on Linux and Windows systems on CRAN.

    # three new ways to compare fit1 to the intercept-only model
    z1 <- D1(fit1, fit0)
    z2 <- mitml::testModels(as.mitml.result(fit1), as.mitml.result(fit0), df.com = 21)
    z3 <- D1(fit1)

with error 

    test_check("mice")
         ── 1. Error: (unknown) (@test-D1.R#13)     ────────────────────────────────────────
     Non-numeric argument to mathematical function
     1: D1(fit1, fit0) at testthat/test-D1.R:13
     2: testModels(fit1, fit0, method = "D1", df.com = df.com)
     3: pf(val, k, v)
 
I could not reproduce on Mac OS (R 3.5.1). As a temporary measure I have outcommented the tests, but there is something fishy going on that needs to be resolved.

**Comment by simongrund1** [comment]
Stef, I think the error is a result of the check:

```r
test_that("compares fit1 to the intercept-only model", {
   expect_identical(z1$result, z2$test)
   expect_identical(z1$test, z3$test)
})
```
There is no slot `test` in `z1` and `z3` (the slot is called like that in `mitml` but not `mice`). It should work with:

```r
test_that("compares fit1 to the intercept-only model", {
   expect_identical(z1$result, z2$test)
   expect_identical(z1$result, z3$result) # change "test" to "result"
})
```

The results all seem fine.

```r
z1$result
#       F.value df1      df2     P(>F)       RIV
# [1,] 0.124502   3 17.94069 0.9443986 0.2177426
z2$test
#       F.value df1      df2     P(>F)       RIV
# [1,] 0.124502   3 17.94069 0.9443986 0.2177426
z3$result
#       F.value df1      df2     P(>F)       RIV
# [1,] 0.124502   3 17.94069 0.9443986 0.2177426

identical(z1$result, z2$test)
# [1] TRUE
identical(z1$result, z3$result)
# [1] TRUE
```

 I am on Linux, not sure why there is a difference between platforms.

**Comment by stefvanbuuren** [comment]
Simon, thanks, that may be another problem (though it worked fine until now). 

The reported crash happens already before that, while running `z1 <- D1(fit1, fit0)`, but the statement runs fine on Mac.

**Comment by stefvanbuuren** [comment]
See #132 for the diagnosis and cure
