### ISSUE TITLE
Return probabilities instead of values with an ordinal variable

### ISSUE THREAD

**Issue by ThomasWilli** [stefvanbuuren/mice#131]
Hi!

Thank you for your great package, it is of great use! I do have a question though. I'm adding a method for imputation to mice (or am trying to). I'd like it to return the probabilities for each answer category (there are five). I thought that I'd just modify your function, however, things seem more complicated... 

First, some example data:
    
    df1 <- data.frame(x1=rnorm(100, 0, 1),
                  x2=as.factor(sample( letters[1:5], 100, replace=T)),
                  x3=runif(100, 0, 1),
                  x4=as.factor(sample(letters[1:5], 100, replace=T)),
                  u=factor(sample( letters[1:5], 100, replace=T), levels=c("a", "b", "c", "d", "e"), ordered=T))
    set.seed(1)
    create.na <- sample( 1:nrow(df1), 25)
    df1$u[create.na] <- NA

Second, I changed the code from the package accordingly: 

    mice.impute.rfown <- function(y, ry, x, wy = NULL, ntree = 10, ...){
         if (is.null(wy)) wy <- !ry
         if (!requireNamespace("randomForest", quietly = TRUE))
         stop("Package 'randomForest' needed fo this function 
         to work. Please install it.",  call. = FALSE)
  
      onetree <- function(xobs, xmis, yobs, ...){
           fit <- randomForest::randomForest(x = xobs, y = yobs, ntree = 1, ...)
    
         probs <- predict(object = fit, newdata = xmis, type="prob")
         return(probs)
          }

    ntree <- max(1, ntree)  # safety
    nmis <- sum(wy)
    xobs <- x[ry, , drop = FALSE]
    xmis <- x[wy, , drop = FALSE]
    yobs <- y[ry]
    
    forest <- sapply(seq_len(ntree), FUN = function(s) onetree(xobs, xmis, yobs))
    pr.probs <- Reduce("+", forest)/10
    return(pr.probs)
    }

    micerf <- mice(df1, method="rfown")

    container <- as.data.frame(micerf$imp$u)
    head(container)

           1    2    3    4    5
     4   <NA> <NA> <NA> <NA> <NA>
     5   <NA> <NA> <NA> <NA> <NA>
     7   <NA> <NA> <NA> <NA> <NA>
     10  <NA> <NA> <NA> <NA> <NA>

If I print steps from my imputation function to the console, it prints correctly (meaning not `NA`s but values). It seems that `mice` is not able to return more data than observed missings? How can I work around this?

Thanks!

**Comment by stefvanbuuren** [comment]
`mice` expects that the type of data returned by the `mice.impute.rfown()` function is the same as the type of the `y` variable. Here you are returning a numeric variable, and `mice` tries to stuff that into an ordered factor. `mice` cannot do that.

**Comment by stefvanbuuren** [comment]
I do not understand why you would want to do this at all. We would be mixing different measurement scales.

**Comment by stefvanbuuren** [comment]
I am closing now I feel there is no need to support this feature.

**Comment by ThomasWilli** [comment]
The project I'm workin on is evaluating the performance of several different imputation methods. In order to calculate some quantities of interest it would be very helpful to get the probabilities as well...

**Comment by ThomasWilli** [comment]
In order to get an idea of the distance between imputed and true data for categorical variables, we would like to consider choice probabilities. Therefore, to obtain probabilities from within `mice` or it's corresponding method would be very helpful...
