### ISSUE TITLE
Flexible squeeze function

### ISSUE THREAD

**Issue by esmd** [stefvanbuuren/mice#134]
Dear Stef Van Buuren,

I want to impute my data such that the imputed values are constrained between say x1 and x2. This can of course be done with a `squeeze` function. However the function substitutes imputed values with either a lower or upper bound value depending on whether the imputed value was below or above the bounds. 

I had many values to impute and with this condition and I was not happy with same values (lower/upper bounded values). I customised the squeeze function so that it sample values between the bounds. Below is my modification that you could consider 

`sqzCust <- function (x, bounds = c(min(x[r]), max(x[r])), r = rep.int(TRUE, 
                                                           length(x)), n) 
{
  if (length(r) != length(x)) 
    stop("Different length of vectors x and r")
  x[x < bounds[1]] <- sample(bounds[1]: bounds[2], n) 
  x[x > bounds[2]] <- sample(bounds[1]: bounds[2], n)
  return(x)
}`

where `n` is the number of missing values

**Comment by stefvanbuuren** [comment]
Thanks for the suggestion. This seems a useful addition. The above procedure draws values `min, min + 1, min + 2, ...` until `max`. An alternative could be to draw from the uniform distribution between the minimum and maximum. We may also extend use parametric distributions. The `n` parameter could probably be calculated from `r` and we need to think about the role of `where` argument.

I hardly ever use `squeeze()` since I use predictive mean matching, which guarantees imputes within bounds.

**Comment by esmd** [comment]
I also use pmm but I wanted to improve my imputations. 

Consider a monthly time series data for say seven years with its associated auxiliary variables. However the response variable for one year is missing but its respective quarterly totals are available from a different source. The interest is to fit a model using monthly data and the data itself is variable over the years. In this case, I want to impute the missing monthly values such that their quarterly total is about what is available from the second source. What I'm trying to do is improve my imputations using other available information since the values vary over years.

I like your suggestion of drawing from a uniform distribution between min and max. Your suggestion of extending to parametric distribution is also interesting. Let me think about the `where` argument since it was not an issue in my current case but needs to be considered in the general case

**Comment by gerkovink** [comment]
It seems that predictive ratio matching is what you would want. Have a look at chapter 5 in [my dissertation](https://drive.google.com/file/d/0ByMrx8Lhz-a4dEMtTTZLRWcyUHM/view?usp=sharing).

**Comment by esmd** [comment]
@gerkovink  thanks for your input and for sharing your dissertation. I've started reading chapter and it seems that is exactly what I needed. I wasnt aware about PRM :) 

I will now close this
