### ISSUE TITLE
Print warning when `mice()` is used with deprecated arguments

### ISSUE THREAD

**Issue by simongrund1** [stefvanbuuren/mice#137]
Since the update to 3.0.0, `mice()` no longer supports older argument names. This causes problems with previously published examples that used earlier versions of `mice` (< 3.0.0). For example, `mice()` will no longer use the imputation methods specified with `imputationMethod` and will use default methods instead (see the examples in Grund, Lüdtke, & Robitzsch, 2018). The user will not be aware of this unless the default methods happen to produce errors.

Would it be possible to include a check in the `mice()` call that prints a warning when this happens? Specifically, I think it'd be a good idea to check the list of arguments passed to `mice()` for outdated argument names and then print a warning for each of these.

Below is a function that could be included with the other checks and called in `mice()` by passing the "three dots":

```r
check.deprecated <- function(...){
  # print warnings for deprecated argument names
  nms <- names(list(...))
  replace.args <- list(imputationMethod = "method",
                       defaultImputationMethod = "defaultMethod",
                       form = "formulas")

  wrn <- names(replace.args) %in% nms
  if(any(wrn)){
    for(i in which(wrn)){
      msg <- paste0("The '", names(replace.args)[i], "' argument is no longer supported. Please use '",
                    replace.args[i], "' instead.")
      warning(msg)
    }
  }

  invisible(NULL)
}
```

This prints a warning message for every deprecated argument name, telling users what the argument is called now:

```
Warning messages:
1: In check.deprecated(...) :
  The 'imputationMethod' argument is no longer supported. Please use 'method' instead.
2: In check.deprecated(...) :
  The 'form' argument is no longer supported. Please use 'formulas' instead.
```

The list defined in the function can be extended to handle future cases. The warning could be followed by a hard `stop()`, but that would mean that function authors would not be able to use the old arguments names either, so I didn't do that.

Would it be possible to include something like this? I can offer to prepare a pull request but wasn't sure whether and how you would like to include such a check.

Best wishes,
Simon

**Comment by simongrund1** [comment]
Dear Stef,

a gentle nudge toward this issue. Have you had any time to look into this?

Thanks in advance and best wishes,
Simon

**Comment by stefvanbuuren** [comment]
Simon, thanks for the reminder. Still on the to do list. Stef.

Van: Simon Grund <notifications@github.com>
Beantwoorden - Aan: stefvanbuuren/mice <reply@reply.github.com>
Datum: donderdag 11 oktober 2018 om 11:13
Aan: stefvanbuuren/mice <mice@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [stefvanbuuren/mice] Print warning when `mice()` is used with deprecated arguments (#137)


Dear Stef,

a gentle nudge toward this issue. Have you had any time to look into this?

Thanks in advance and best wishes,
Simon

**Comment by stefvanbuuren** [comment]
Simon, thanks. Now added to 3.3.1.
