### ISSUE TITLE
nelsonaalen fails when another column is named time or status 

### ISSUE THREAD

**Issue by matthieu-faron** [stefvanbuuren/mice#140]
Dear Stef,
Thanks for the great work on MICE

When using the nelsonaalen function, is another column of the data frame is already names time or status, the function does not take the provided column but the ones named "time" or "status" 

Here we want to calculate the nelson aalen estimator with the column time and alive, but the function takes the status column...
```

df <- data.frame(time = 1:10, status = sample(c("a", "b"), 10, replace = TRUE), alive = sample(c(0, 1), 10, replace = TRUE))

mice::nelsonaalen(df, time, alive)
```

If you find this issue important enough to be corrected, a simple fix would be to supress the data argument from the coxph calls in the function, as time and status are also calculated outside the data frame in your function 
```

function (data, timevar, statusvar) 
{
  if (!is.data.frame(data)) 
    stop("Data must be a data frame")
  timevar <- as.character(substitute(timevar))
  statusvar <- as.character(substitute(statusvar))
  time <- data[, timevar]
  status <- data[, statusvar]
  hazard <- basehaz(coxph(Surv(time, status) ~ 1)) ### data=data supressed here ####
  idx <- match(time, hazard[, "time"])
  return(hazard[idx, "hazard"])
}
```

Kind regards,

**Comment by stefvanbuuren** [comment]
OK, thanks. Incorporated in `mice 3.3.1`.
