### ISSUE TITLE
Problem with imputation method in mice 3.3.0

### ISSUE THREAD

**Issue by ema261989** [stefvanbuuren/mice#143]
Hi,

I installed mice 3.3.0, my R version is 3.4.2. It seems that command mice() automatically sets imputation method for all variables to 'pmm'. When I run this script from the package documentation:

G <- 250 # number of groups
n <- 20 # number of persons
beta <- .3 # regression coefficient
rho <- .30 # residual intraclass correlation
rho.miss <- .10 # correlation with missing response
missrate <- .50 # missing proportion
y1 <- rep( rnorm( G , sd = sqrt( rho ) ) , each=n ) + rnorm(G*n , sd = sqrt( 1 - rho ))
w <- rep( round( rnorm(G ) , 2 ) , each=n )
v <- rep( round( runif( G , 0 , 3 ) ) , each=n )
x <- rnorm( G*n )
y <- y1 + beta * x + .2 * w + .1 * v
dfr0 <- dfr <- data.frame( "group" = rep(1:G , each=n ) , "x" = x , "y" = y , "w" = w , "v" = v )
dfr[ rho.miss * x + rnorm( G*n , sd = sqrt( 1 - rho.miss ) ) < qnorm( missrate ) , "y" ] <- NA
dfr[ rep( rnorm(G) , each=n ) < qnorm( missrate ) , "w" ] <- NA
dfr[ rep( rnorm(G) , each=n ) < qnorm( missrate ) , "v" ] <- NA
#....
# empty mice imputation
imp0 <- mice( as.matrix(dfr) , maxit=0 )
predM <- imp0$predictorMatrix
impM <- imp0$method
#...
# multilevel imputation
predM1 <- predM
predM1[c("w","y","v"),"group"] <- -2
predM1["y","x"] <- 1 # fixed x effects imputation
impM1 <- impM
impM1[c("y","w","v")] <- c("2l.pan" , "2lonly.norm" , "2lonly.pmm" )
# y ... imputation using pan
# w ... imputation at level 2 using norm
# v ... imputation at level 2 using pmm
imp1 <- mice( as.matrix( dfr ) , m = 1 , predictorMatrix = predM1 ,
imputationMethod = impM1 , maxit=1 , paniter=500)

and I ask for imp1$method the result is: 

> imp1$method
group     x     y     w     v 
   ""    "" "pmm" "pmm" "pmm" 

I double checked impM1:

> impM1
        group             x             y             w             v 
           ""            ""      "2l.pan" "2lonly.norm"  "2lonly.pmm" 

Same result if I change imputation methods for some variables (eg logreg). I used the same script in an online compiler (rdrr.io/snippets, R version 3.4.1, mice 2.3.0) and the result is correct:

imp1$method
        group             x             y             w             v 
           ""            ""      "2l.pan" "2lonly.norm"  "2lonly.pmm" 

I tried to downgrade to R version 3.4.1 in my pc, but the result is again that all methods are "pmm". Unfortunately I have problems installing older versions of mice and I can't give more information.
Is it a bug or I'm missing something?

Thank you very much for your work,
Emanuele

**Comment by gerkovink** [comment]
Hi Emanuele,

`imputationMethod` has been deprecated. Use `method` instead.

All the best,

Gerko

**Comment by ema261989** [comment]
Hi Gerko,

thank you very much!

Emanuele
