### ISSUE TITLE
Imputation Fails When Variables Are Omitted From Predictor Matrix and Method

### ISSUE THREAD

**Issue by morgandtx** [stefvanbuuren/mice#144]
I am using mice to impute missing values for a large dataset with many variables. I need to impute values for only a subset of those variables and certain variables must be exclude from the imputation equations (for substantive reasons). The issue is that when specifying "" for the method corresponding to the variable for exclusion and excluding a variable by setting its column values to 0 in predictorMatrix, the imputation process fails and no values are imputed. 

Please see attached 
[mice_error_181002_v1.docx](https://github.com/stefvanbuuren/mice/files/2439096/mice_error_181002_v1.docx)
for a reproducible example.

**Comment by stefvanbuuren** [comment]
In your example, you don't impute `hyp` but use it as predictor for imputing `bmi`. Four values are imputed (e.g. row 3 bmi). However, it is not possible to impute missing values in `bmi` for rows where `hyp` is missing, and hence `mice` sets these entries to missing.

**Comment by stefvanbuuren** [comment]
Assume the expected behaviour as described above resolves your question, so am closing now.
