### ISSUE TITLE
Failure to impute a missing value in a balanced table

### ISSUE THREAD

**Issue by ellisp** [stefvanbuuren/mice#150]
This behaviour seems to be a bug:

```R
library(mice)

data <- data.frame(
  x = c("a", "b", "a", "b"),
  y = c("A", "A", "B", "B"),
  z = c(8, NA, 8, 9)
)

data_imp <- mice(data)
mice::complete(data_imp, 1)
```

which returns

```
  x y  z
1 a A  8
2 b A NA
3 a B  8
4 b B  9
```
That is, there's no imputed value in any of the "complete" datasets for the second value of z.

Things that *don't* help including explicitly telling `mice` `where` the missing value is, or trying different imputation methods.

Things that *do* help include changing the third value of z to anything other than an 8 or 9.

**Comment by ellisp** [comment]
OK, I worked it out from reading [your material here](https://stefvanbuuren.name/fimd/sec-toomany.html), sorry I logged the issue.

z isn't imputed because it is apparently collinear with x.  This behaviour can be overridden with 

```R
data_imp <- mice(data, where = is.na(data), print = FALSE, remove.collinear = FALSE)
mice::complete(data_imp, 1)
```

**Comment by stefvanbuuren** [comment]
Thanks. Actually 

```r
data_imp <- mice(data, print = FALSE, remove.collinear = FALSE)
```

is enough to force imputation of collinear variables. Related to #48. 

I also [write](https://stefvanbuuren.name/fimd/sec-toomany.html#finding-problems-loggedevents)

> Note that setting remove.constant = FALSE or remove.collinear = FALSE bypasses usual safety measures in mice, and could cause problems further down the road.

We see that `mice` will still throw some warnings because of the collinearity. The recommended approach is to specify the `predictorMatrix` argument. In your case, we specify

```r
pred <- make.predictorMatrix(data)
pred["z", "x"] <- 0
data_imp <- mice(data, print = FALSE, pred = pred, remove.collinear = FALSE)
complete(data_imp, 1)
```
