### ISSUE TITLE
Request for Conditional imputation

### ISSUE THREAD

**Issue by simon-r-white** [stefvanbuuren/mice#152]
Proposal to consider adding a method to implement conditional imputation.

When comparing ``mice()`` capabilities to the ``mi chained:`` within Stata, Stata includes the ability to set conditional's such that only certain elements are imputed based on another column (which itself may be imputed).

Within ``mice()`` we can specify a global ``where`` to skip imputing certain entries. However, this cannot handle the situation where the desire to skip imputing is conditional itself on another imputed entry.

I imagine one way to address this would be to add a ``pre`` type argument akin to the current ``post`` type argument, which the ability to adjust the missingness indicator matrix; but there might be a better (or more ``mice()`` way of achieveing this).

Another option would be to write custom ``mice.impute.xxx`` functions, but that seems extreme (and not very user friendly).

Thoughts?

**Comment by stefvanbuuren** [comment]
There are several ways to do conditional imputation in `mice`.  The simplest method is to impute all cells, and then overwrite imputed values that meet the condition with `NA` after imputation.

Example: Suppose in `nhanes` we want to impute `chl` only if `hyp == 2`. 

```{r}
# this will overwrite the imputed values with hyp == 2 with NA
library(mice)
imp <- mice(nhanes, print = FALSE, seed = 1)
cmp <- complete(imp, action = "long", include = TRUE)
cmp[cmp$.imp >= 1 & cmp$hyp == 2, "chl"] <- NA
imp2 <- as.mids(cmp)
imp2$imp

...

$hyp
   1 2 3 4 5
1  1 1 1 1 1
4  2 1 1 2 1
6  2 1 1 1 1
10 1 1 2 1 1
11 1 1 1 1 1
12 1 2 2 1 2
16 1 1 1 1 1
21 1 1 2 1 1

$chl
     1   2   3   4   5
1  187 187 187 238 131
4   NA 218 186  NA 187
10 218 187  NA 187 206
11 187 187 187 204 187
12 186  NA  NA 187  NA
15 187 187 187 131 187
16 187 187 238 238 187
20  NA  NA  NA  NA  NA
21 187 187  NA 206 187
24 218 284 206 186 218
```

It is straightforward to adapt this script to other conditions. Would this address your problem?

**Comment by stefvanbuuren** [comment]
Related discussion using more complex approaches are in #43 and #125.

**Comment by simon-r-white** [comment]
@stefvanbuuren, fully agree that the ``post`` argument works to solve part of this type of imputation ([Stata's conditional option](https://www.stata.com/manuals13/mimiimpute.pdf#mimiimputeRemarksandexamplesConditionalimputation)).

However, I believe that ``Stata``'s ``by`` option goes a bit further and restricts the rows used to perform the imputation [see Stata manual](https://www.stata.com/manuals13/mimiimpute.pdf#mimiimputeRemarksandexamplesImputingonsubsamples).

For that type of conditional imputation the suggestion above (altering the values post imputation using the ``post`` argument) would include all rows of the data frame. Whereas a ``pre`` argument, where we could restrict the to a subset, might be one way to code this.

Really, I'm thinking about Stata's conceptual framework with the separation of the [imputation and estimation samples](https://www.stata.com/manuals13/mimiimpute.pdf#mimiimputeRemarksandexamplesImputationandestimationsamples), and how to best consider/implement this within ``mice()``'s framework.

**Comment by stefvanbuuren** [comment]
It's not entirely clear to me what problem you are trying to solve. 

If you develop a small example, I would be happy to think about how `mice`  could address the problem.

**Comment by stefvanbuuren** [comment]
Closing in the anticipation of a reproducible example. Feel free to re-open.
