### ISSUE TITLE
Creating imputations that do not exceed a value of another variable

### ISSUE THREAD

**Issue by lphan6** [stefvanbuuren/mice#153]
Dear Stef van Buuren,

I'm reading your textbook and is trying to implement conditional imputation using "post()" and "squeeze()" but did not really work. I wonder if you can help me with the problem.

Here is an example of my data. It has three variables: virus_copy (which has more than 50% of NA values; , lod = detection limit; and presence = positive sample (yes/no). 
My question is how can I impute NA values of virus_copy that are greater than 0 but less than the detection limit.  Thank you!

```{r}
library(mice)
library(sqldf)

data<-data.frame(virus_copy = sample(c(rlnorm(100, 0, 1), rep(NA,50))), lod = sample (c(rlnorm(2,0,1))))
data$presence<-ifelse(data$virus_copy == "NA", "no", "yes")
data$presence[is.na(data$presence)]<-"no"
View(data)

# imputation
data.ini<-mice(data, maxit =0)
post<-data.ini$post
post["data$virus_copy"] <- "imp[j] <- squeeze(imp[j], bounds = c(0, (data$lod)))"
method=data.ini$method
method
data.imp.amp<-mice(data, print=TRUE, method=method, post = post, m=1)
m1<-complete(data.imp.amp, action=1)

# checking if NA imputed values of virus_copy are less than LOD
check<-(sqldf('SELECT *  FROM m1 WHERE presence != "yes"'))
View(check)
check$subtraction <- (check$virus_copy - check$lod)
sum(check$subtraction > 0)
```

**Comment by stefvanbuuren** [comment]
I think it is easier to use `pmin()`. The following script will never impute values for `virus_copy` that are larger than `lod`.

```{r}
library(mice)

set.seed(1)
data <- data.frame(virus_copy = sample(c(rlnorm(100, 0, 1), rep(NA, 50))), 
                   lod = sample (c(rlnorm(2, 0, 1))))

# imputation
data.ini <- mice(data, maxit = 0)
post <- data.ini$post
post["virus_copy"] <- "imp[[j]][, i] <- pmin(imp[[j]][, i], data[(!r[, j]) & where[, j], 'lod'])"
imp <- mice(data, print = FALSE, post = post, m = 1)
m1 <- complete(imp)

# checking if NA imputed values of virus_copy are less than LOD
check <- m1[is.na(data$virus_copy), ]
check$subtraction <- check$virus_copy - check$lod
sum(check$subtraction > 0)
```

**Comment by lphan6** [comment]
Thank you very much for your response! I ran the code and got an error below. I wonder if you are using an upgraded mice library that has the pmin() function?

 # imputation
> data.ini <- mice(data, maxit = 0)
> post <- data.ini$post
> post["virus_copy"] <- "imp[[j]][, i] <- pmin(imp[[j]][, i], data[(!r[, j]) & where[, j], 'lod'])"
> imp <- mice(data, print = FALSE, post = post, m = 1)
Error in `[.data.frame`(data, (!r[, j]) & where[, j], "lod") : 
  object 'where' not found

**Comment by stefvanbuuren** [comment]
The `where` argument was introduced more than a year ago. Code should run with `mice 3.0.0` and above.
