### ISSUE TITLE
Request for more flexible plot functionality in md.pattern

### ISSUE THREAD

**Issue by annette987** [stefvanbuuren/mice#154]
The md.pattern function is really helpful but it would be great to have some minimal options to modify the plot. The most important one I see is a str (string rotation) option to rotate at least the labels on the top axis so that they don't run into each other and become illegible. E.g 
![image](https://user-images.githubusercontent.com/29032713/48814241-2c597800-ed8e-11e8-8ef9-6e9075619ff6.png)

Other options, such as label sizing would also be welcome, but not as essential.
Forgive me if this is possible already, but I have not seen an example of it.
Thanks.

**Comment by stefvanbuuren** [comment]
Related to #160

**Comment by stefvanbuuren** [comment]
`mice 3.3.5` adds the `rotate.names` argument to `md.pattern()`

**Comment by ahcyip** [comment]
Hi, I made a similar fix to srt and adj to rotate the names, but then I found that the column names were getting cut off the graph after rotation.
I think you'll want to adjust
plot.window(xlim=c(-1, ncol(R) + 1), ylim=c(-1, nrow(R) + 1), asp=1)
to
plot.window(xlim=c(-1, ncol(R) + 1), ylim=c(-1, nrow(R) + length_of_longest_colname), asp=1)

**Comment by ahcyip** [comment]
I suggested a fix https://github.com/stefvanbuuren/mice/pull/170

**Comment by NienkeSchouten** [comment]
Dear stefvanbuuren or ahcyip (or anyone else),

Is it also possible to scale the x- and y-axis? I am using this for my IPD which includes 3849 observations of 57 variables. My missing pattern figure is now so small that I cannot read the figure. Thank you in advance!

**Comment by proof-by-accident** [comment]
Hi all. I have just started using `mice` and am loving it, but would like to second what NienkeSchouten mentioned. I'm dealing with a rather large dataset, and it would be nice to be able to control the size of the plots produced by `md.pattern`. Thanks everyone for all the heard work!

**Comment by KaiyeYang-git** [comment]
Can we add a title for md.patterns?

**Comment by thomvolker** [comment]
@KaiyeYang-git Please check out the newly released package [`ggmice`](https://github.com/amices/ggmice). It contains a function to plot missing data patterns with ggplot functionality (see the `plot_pattern()` function description [here](https://amices.org/ggmice/reference/plot_pattern.html)), and thus allows for greater flexibility than the regular `mice` functions.
