### ISSUE TITLE
quickpred() eliminates predictors with no missing values

### ISSUE THREAD

**Issue by maciejrosolowski** [stefvanbuuren/mice#158]
The line:
`predictorMatrix[colSums(!r) == 0, ] <- 0`
in quickpred() eliminates predictors with no missing values. Should the line be:
`predictorMatrix[colSums(r) == 0, ] <- 0`
instead? That second line would eliminate predictors containing only missing values.

**Comment by stefvanbuuren** [comment]
I think it is correct as is. The statement simply says that we do not need any predictors for variables that are complete, e.g. 

```r
> quickpred(nhanes)
    age bmi hyp chl
age   0   0   0   0
bmi   1   0   1   1
hyp   1   0   0   1
chl   1   1   1   0
```

makes the row for `age` equal to zeroes.

**Comment by maciejrosolowski** [comment]
Ah, thank you, my mistake. Sorry for opening this issue.
