### ISSUE TITLE
Is the order of rows and columns preserved by mice?

### ISSUE THREAD

**Issue by surh** [stefvanbuuren/mice#169]
The answer is probably yes, but I haven't found this explicitly stated in the documentation or elsewhere.

Is the order of the rows and columns of the imputed dataset in mice (after `complete`) guaranteed to be always the same as in the original input data with missing values?

**Comment by stefvanbuuren** [comment]
The order is the same, but `complete()` may add additional columns (`.imp`, `.id`) in some cases.
