### ISSUE TITLE
Error in P-value calculation

### ISSUE THREAD

**Issue by SolIoa** [stefvanbuuren/mice#171]
Dear authors, 
Firstly, let me congratulate you for your work. For a personal project, I tried to recreate the pooling of estimates from multiply imputed datasets and I found the documentation of [mice](https://cran.r-project.org/web/packages/mice/index.html) and instructions in [Flexible imputation of Missing Data](https://stefvanbuuren.name/fimd/want-the-hardcopy.html) valuable. However, when my output is compared to `mice` output, there are some differences after the 3rd-4th decimal of the p-values in some cases, whereas all other estimates (total variance, lambda) are exactly the same. After inspecting the mice functions, I found that the difference is caused by the  `max(x$df, 0.001)`, of the p-value estimation i.e
`p.value <- 2 * (1 - pt(abs(statistic), max(x$df, 0.001)))` in the `summary.mipo` function. 

For start, I would like an explanation for this (maximum of `df` and 0.001) as I did not find any comment about it, neither in Stef's book, nor in any other of the referenced papers. On the other hand, it is mentioned in Stef's book that a value of less than 1 for the degrees of freedom (df) is [nonsensical, so we should refrain from any testing due to lack of information.](https://stefvanbuuren.name/fimd/sec-whyandwhen.html). Hence, I do not really understand the need of ensuring that the degrees of freedom are greater than 0.001. 

Secondly, the `max(x$df, 0.001)` line causes the estimation of the p-value for each coefficient to select the maximum of the vector `df` as degrees of freedom for all p-value estimations. I have been busting my head around this for few days but I do not have a real reason why this should be the case. On the other hand, this may be a specification, easily fixable, but I still do not understand the role of 0.001 to justify it. 

Theoretically, this should not cause any problems for statistical significance, a value little above or below 0.05 does not make much difference. However. in cases of multiple testing the story may be well different when trying to detect a signal. 
Kind regards,

**Comment by stefvanbuuren** [comment]
The degrees of freedom must be a positive number, so the `max()` function is simply there to prevent crashes when the calculated number of degrees of freedom is negative.

**Comment by SolIoa** [comment]
Hello and thank you for the response. 
 
OK, it makes sense. 
However, for the second issue, I do not understand why we should use the max degrees of freedom from all predictors, instead of each predictor's own degrees of freedom. Maybe I was not clear enough before, and I was using the term coefficients lightly, apologies for that. Below is an example:

```r
library(mice)
data(nhanes)
summary(nhanes)
imp <- mice(nhanes)
fits <- with(imp, expr = lm(hyp ~ bmi + chl))
x<- pool(fits)[[3]]
x[, c(1, 5, 6) ]
```

| | estimate | dfcom | df |
| --- | --- | --- | --- |
| (Intercept) | 0.652348960 | 22 | 15.51787 |
| bmi | -0.009181324 | 22 | 18.57621 |
| chl | 0.004187183 | 22 | 14.24487 |

Then for every pooled p- value and for every predictor, the value that is used is
```r
max(x$df, 0.001)
```
[1] 18.57621

**Comment by stefvanbuuren** [comment]
OK, thanks. I made a programming error. It should be

`2 * (1 - pt(abs(statistic), pmax(x$df, 0.001)))`

I will repair this. 

The error will make P-values appear a little smaller for coefficients that have a high fraction of missing information. Since the test statistic has more impact on the P-value than the degrees of freedom, I don't think the effects of the error are dramatic. Confidence intervals are not affected, only P-values for testing the parameter against zero.

Thanks for pointing out.

**Comment by stefvanbuuren** [comment]
`mice 3.4.1` contains the fix
