### ISSUE TITLE
different versions producing different results

### ISSUE THREAD

**Issue by jakumi** [stefvanbuuren/mice#172]
i have an inconsistency problem running the following code on different versions of mice

```
library(mice)
df <- as.data.frame(cbind(c(0,1,NA,0,1,NA), c(1,1,1,0,0,0)))
imp <- mice(data=df, m=5, diagnostics = TRUE, seed=123)
complete(imp, "repeated", inc=FALSE)
packageVersion("mice")
```

produces different results (omitting progress output from mice call) slightly old ubuntu:

    > complete(imp, "repeated", inc=FALSE)
      V1.1 V1.2 V1.3 V1.4 V1.5 V2.1 V2.2 V2.3 V2.4 V2.5
    1    0    0    0    0    0    1    1    1    1    1
    2    1    1    1    1    1    1    1    1    1    1
    3    1    1    1    0    0    1    1    1    1    1
    4    0    0    0    0    0    0    0    0    0    0
    5    1    1    1    1    1    0    0    0    0    0
    6    1    0    0    1    1    0    0    0    0    0
    > packageVersion("mice")
    [1] ‘2.46.0’

on a newer arch linux I got:

    > complete(imp, "repeated", inc=FALSE)
      V1.1 V1.2 V1.3 V1.4 V1.5 V2.1 V2.2 V2.3 V2.4 V2.5
    1    0    0    0    0    0    1    1    1    1    1
    2    1    1    1    1    1    1    1    1    1    1
    3    0    1    0    0    0    1    1    1    1    1
    4    0    0    0    0    0    0    0    0    0    0
    5    1    1    1    1    1    0    0    0    0    0
    6    0    1    0    0    0    0    0    0    0    0
    > packageVersion("mice")
    [1] ‘3.0.0’

(results in 3.4.0 are the same in 3.0.0)

Lines 3 and 6 (where NA values were) are quite different from one another, and the derived values will likely be too.

Now I get that one shouldn't rely on backwards compatiblity on major version upgrades, ... but apparently the behavior changed? 

I assume this change in behavior wasn't intended. Since it also wasn't communicated, I suspect this to be a bug

**Comment by stefvanbuuren** [comment]
`mice 3.0` is completely rewritten internally, and so you will not get exactly the same imputations because the random generator is called at different points. 

This is unlikely to be a problem in practice, but if you want exact replication, there is no alternative but to install the old version.

**Comment by jakumi** [comment]
I was afraid you'd say that. Thanks anyway. ;o/

**Comment by gerkovink** [comment]
For what it's worth: `mice 2.46.0` was mostly based on regression estimation with a default ridge penalty to ensure computational continuity. From `mice 3.0` onwards, the algorithm falls back on ridge regression if, and only if, the default QR decomposition or singular value decomposition fail. To remain closer to earlier results, with the only difference being due to the random number generation, one might use   
```r
imp <- mice(data=df, seed = 123,  ls.meth = "ridge")
```
although I'd advice to stick to the default in `mice 3.0+` as the ridge parameter introduces a tiny bit of bias. Like @stefvanbuuren said, the redesign makes it unlikely to obtain exactly the same results, as the sequence call to the random number generator in the improved algorithm is different.

**Comment by gerkovink** [comment]
See the below code for two examples: one where the old and new versions of `mice` yield identical results, and one where they differ.

- `mice 2.46.0`
```r
> devtools::install_version(package = "mice", version = "2.46.0", repos = "http://cran.us.r-project.org")
> library(mice)
> version()
[1] "mice 2.46.0 2017-10-23 /Library/Frameworks/R.framework/Versions/3.4/Resources/library"
> imp.old <- mice(nhanes, seed = 123, print = FALSE)
> imp.old2 <- mice(boys, seed = 123, print = FALSE)
```

- `mice 3.4.1`
```r
> devtools::install_github("stefvanbuuren/mice")
> version()
[1] "mice 3.4.1 2019-03-28 /Library/Frameworks/R.framework/Versions/3.4/Resources/library"
> imp.new <- mice(nhanes, seed = 123, print = FALSE, ls.meth = "ridge")
> imp.new2 <- mice(boys, seed = 123, print = FALSE, ls.meth = "ridge")
```
and the evaluations
```r
> identical(complete(imp.old, "long"), complete(imp.new, "long"))
[1] TRUE
> identical(complete(imp.old2, "long"), complete(imp.new2, "long"))
[1] FALSE
```
