### ISSUE TITLE
as.mids incorrect when input long data not sorted

### ISSUE THREAD

**Issue by maitraag** [stefvanbuuren/mice#173]
as.mids needs input data be sorted by .imp, otherwise lines 31 and 32 in the function probably throw an error (or replace incorrect cells, at least). Pleace amend the help file with the note that "long" should be sorted by .imp and the rows in each imputation must be in the same order. (And optionally check within as.mids if all non-imputed cells have the same values within all imputed datasets.)

**Comment by stefvanbuuren** [comment]
Thanks. I added a warning note to the documentation of `as.mids()` in `mice 3.4.3`.

I didn't add any additional error checking or sorting.
