### ISSUE TITLE
plot.mids failure

### ISSUE THREAD

**Issue by santsang** [stefvanbuuren/mice#174]
Hi

I got this message when I use plot():

Error in eval(i, data, env) : object 'varx' not found

Further information: I used "where" option to skip imputing certain entries.

Any possible help is much appreciated.

All the best

Sandro

**Comment by stefvanbuuren** [comment]
I am afraid that I cannot reproduce this without some more info.

**Comment by santsang** [comment]
Thank you very much for your reply.  The problem was not plot() or having NA in my mids.  The problem was the erratic computer.  I restart R and things were running fine.  Sandro
