### ISSUE TITLE
confidence intervals via pool

### ISSUE THREAD

**Issue by rumbach31** [stefvanbuuren/mice#176]
Can you clarify how the confidence intervals are being computed when you include conf.int=TRUE for the pool command? And are there additional options (perc, boot, etc), the way there are with the typical confint command. I should mention I'm using this with lmer, not lm.

**Comment by stefvanbuuren** [comment]
It's just the standard confidence interval, as in https://stefvanbuuren.name/fimd/sec-inference.html#sec:singlepar. The relevant code is in the internal function `mice:::confint.mipo`. It supports the standard parameters as documented in `stats::confint`, and ignores the extended set in `lme4`.
