### ISSUE TITLE
Summary of mipo for glm()'s

### ISSUE THREAD

**Issue by srhaile** [stefvanbuuren/mice#179]
summary.mipo (or rather, process_mipo) throws a warning when "exponentiate = TRUE" even if the fitted model has the correct link:

> imp <- mice(nhanes2, print = FALSE)
> fit <- with(data=imp,exp=glm(hyp~age+bmi,family=binomial))
Warning message:
glm.fit: fitted probabilities numerically 0 or 1 occurred 
> summary(pool(fit), conf.int = TRUE, exponentiate = TRUE)
                estimate    std.error    statistic       df   p.value     2.5 %   97.5 %
(Intercept) 3.633062e-14 3277.0073873 -0.009443407 19.24807 0.9925626 0.0000000      Inf
age40-59    1.247735e+07 3276.9713271  0.004986136 19.24807 0.9960730 0.0000000      Inf
age60-99    1.901732e+07 3276.9727668  0.005114739 19.24807 0.9959717 0.0000000      Inf
bmi         1.762666e+00    0.4184885  1.354464261  8.94037 0.1912759 0.6832992 4.547046
**Warning message:
In process_mipo(z, object, conf.int = conf.int, conf.level = conf.level,  :
  Exponentiating coefficients, but model did not use a log or logit link function**
> sapply(fit$analyses, function(x){x$family$link})
[1] "logit" "logit" "logit" "logit" "logit"

Seems to be because 
```
        if (is.null(x$family) || (x$family$link != "logit" && 
            x$family$link != "log")) {
            warning(paste("Exponentiating coefficients, but model did not use", 
                "a log or logit link function"))
        }
```
looks for pool(fit)$family, which doesn't exist. Seems like a good idea generally to throw a warning here, but I don't see how summary.mipo can access the "family" information...

**Comment by stefvanbuuren** [comment]
Hi, is this different from issue #164?

**Comment by srhaile** [comment]
You're right, it's the same. But it shouldn't give a warning should it? Thanks!

**Comment by stefvanbuuren** [comment]
The warning comes from more rigorous checking in recent `R`. Do not yet know how to evade it, but it's harmless.
