### ISSUE TITLE
Pool compare () function GLM to GLMER

### ISSUE THREAD

**Issue by evelinewiegers** [stefvanbuuren/mice#181]
Hi,

I would like to test the significance of my random effects. 
I have the following model: 

fm1 <- with(dti.mice1, glmer(Treatment ~ (1|Hospital) + Age))

which I would like to compare to model 2 with LRT:

fm2 <- with (dti.mice1, glm(Treatment ~ Age))

I tried the following (both with Wald and Likelihood):
pool.compare (fm1, fm2) 

However, I get the following error:
Error: Model 'fit1' not larger than 'fit0'

Anyone suggestions how to test the importance of my random effects?

**Comment by stefvanbuuren** [comment]
You're comparing `glmer()` to `glm`. I would suggest using the same complete-data function for both analyses.
