### ISSUE TITLE
Summary function with mipo object

### ISSUE THREAD

**Issue by weltenbummler123** [stefvanbuuren/mice#182]
Hi there!

I am using mice for a large meta-analysis project - where I'm implementing the missing value imputation with mice and then running a meta-analytic multilevel mixed-effects model (using the function rma.mv) on the pooled mipo object. Unfortunately, I cannot figure out how to access the full summary of the mipo object. That is, when I use the summary() function to access the output of the mipo object, I only get the following output variables: estimate, std.error, statistic, df, p.value. However, I'm really interested in accessing the variance components (sigma2 estimates) and other descriptives (such as Test for Residual Heterogeneity), which are part of the standard output when calling the summary function on the output of the standard rma.mv function (not using imputation/mice).

I have read here [1] that the column names used from mice 3.0 on employ the names used in the broom package, and that adding "conf.int = TRUE" to the summary function of a mipo object, additionally returns this attribute. However, if I add attributes such as "sigma = TRUE", nothing happens.

I there a way of accessing these attributes (especially the sigma)?

Any hints are appreciated! Thanks a lot in advance.

Caroline

I am using R version 3.6.0 with Mice 3.5.0 on Ubuntu.

[1] https://github.com/stefvanbuuren/mice/issues/92

**Comment by stefvanbuuren** [comment]
Calling `summary()` on a `rma.mv` object calls `summary.rma.mv()`, whereas calling `summary()` on a `mipo` object calls the `summary.mipo()` function. 

If you want the aggregates produced by  `summary.rma.mv()`, then call them on an object of class `rma.mv`. If the complete-data analyses are in object `fit`, then use `summary(fit$analyses[[1]])` to apply `summary.rma.mv()` to the first imputed data set. 

Note that there are `m` of those summaries.
