### ISSUE TITLE
loggedEvents - futher explanation needed

### ISSUE THREAD

**Issue by jaySf** [stefvanbuuren/mice#183]
Hi Stef,
thanks for this great package beforehand!

In [_Flexible Imputation of Missing Data_](https://stefvanbuuren.name/fimd/sec-toomany.html#finding-problems-loggedevents) you nicely explain, what `constant` or `collinear` signalizes in the `meth` column of the `mice(.)$loggedEvents` output. However, I couldn't find anything about other `meth` levels, even not elsewhere, specifically those related to the models, e.g. `pmm`, `logreg`,  `polr` etc.

**Example output**
```
it im           dep    meth           out
1    1  1       age     pmm        age.sq
2    1  1    age.sq     pmm           age
3    1  1      bin1  logreg        sample
4    1  1 bin2Xeduc polyreg         child
5    1  1     happy  logreg child, sample
6    1  1   healthy  logreg child, sample
[...] (6513 more rows)
```
I understand that the `out` column shows the removed variables, but what does the chosen model tell me indicated in the `meth` column?
Could you please elaborate on this? Or perhaps could you point me to a more complete documentation regarding the warning?

Cheers

**Comment by stefvanbuuren** [comment]
`meth` is the imputation method used for the variable under `dep`, and corresponds to the `method` argument of `mice()`.
