### ISSUE TITLE
interaction involving categorical variable: impute strata - rbind strata - add interaction term - as.mids - ...

### ISSUE THREAD

**Issue by sff06** [stefvanbuuren/mice#184]
Dear Professor van Buuren,

I am facing problems when using mice with midastouch to impute missing data of two data strata. The imputation in separate stata is due to having an interaction involving a categorical variable A (and a continuous variable B). The problems concerns the steps afters combining imputed data strata into one mids object. What are the next steps?

Here is how I proceeded:
In van Buuren (2018). Flexible Imputation of Missing Data, p. 176, you suggest to combine the strata using rbind, e.g. `data <- rbind(data1, data2)`. This results in a new mids object.
The next step is to include the interaction term to data.
Using `Cdata=complete(data, "long", include = TRUE, mild = FALSE)` converts the mids object to a data frame that also contains the .imp = 0 with the original data with its missings. Now it is possible to add a column to the data set in which each cell contains the value of the product of the two interacting variables, say AB. (this step also produces NA values in AB for .imp = 0 when the B has missing values).
In order to run my regression model on each imputed data set, we need to reconvert data to a mids object using function as.mids, e.g. `MCdata <- as.mids(Cdata).` If I enter `MCdata` it shows me that the imputation method used is pmm, not midastouch. Due to having already imputed the data, I would assume that I can ignore this issue.
Now I want to run my robust regression model using function adcom from WRS package.
`expr=expression(adcom(cbind(V1, V2, AB), V3, xout = TRUE))` #code adapted from van Buuren (2018), p. 145; V1 and V2 are A and B, V3 is dependent variable
`fit=with(MCdata, eval(expr))`
`fit$analyses`

The estimated regression coefficients for each imputed data set deviate from the coefficients that resulted from analyzing each imputed data set separately. I would guess that this is due to the function with, which seems to impute the data again using pmm. I guess values in AB are also imputed again.
Are these assumptions correct? If yes, is there a way for workarounds (e.g. prohibiting function with to impute data again and just analyze data according to the model within each imputed data set)?

Thank you very much in advance!

Best regards,
Stanley Friedemann

**Comment by stefvanbuuren** [comment]
If `data` is a `mids`-object constructed from two separate `mids` objects, why don't you run something like
```r
fit <- with(data, adcom(V3 ~ V1 + V2 + V1 * V2, xout = TRUE))
```

**Comment by sff06** [comment]
Thank you for your suggestion! This results in the following error message:
Error in dim(data) <- dim : invalid first argument
Called from: array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), 
    NULL) else NULL)
I have no clue how to deal with it. Do you have a suggestion? Many thanks in advance!

**Comment by stefvanbuuren** [comment]
My suggestion is to create a example that reproduces the error on a minimal dataset.

**Comment by sff06** [comment]
I guess my former problem concerning different results for adcom is due to the fact that adcom uses a bootstrap procedure, hence results always differ (slightly). Further, I assume that the second problem from 14 Jul is also due to adcom which needs at first two argument adcom(x,y, ...), x can be a matrix of predictor vectors.
