### ISSUE TITLE
MICE method for Fine & Gray model

### ISSUE THREAD

**Issue by Johnzav888** [stefvanbuuren/mice#185]
Dear Prof. van Buuren,

I recently got my hands on a project where competing risks is the appropriate analysis method. Apparently, missing values are (of course) present! 

In case of cause-specific hazards, it is straight-forwards how to proceed. However, if Fine & Gray model is to be used, a problem arises...

First, does it make sense to pool results from such models ? And of course, if that is indeed statistically appropriate, is there a way to achieve it with mice() ? 

Thank you in advance !

Kind regards,
Ioannis Zavrakidis

**Comment by stefvanbuuren** [comment]
I am not familiar with the Fine & Gray model, so cannot really give you any detailed advice. 

In principle, as long as the model parameters are normally distributed, you can use the standard pooling rules as implemented in `pool()` and `pool.scalar()` in `mice`, so I would just go ahead.

**Comment by Johnzav888** [comment]
Ok then! 

Thanks a lot for your time!
