### ISSUE TITLE
Publish binaries for 3.6.0

### ISSUE THREAD

**Issue by Hirse** [stefvanbuuren/mice#186]
As a casual R user on Windows, I was unable to update mice to the latest version (without installing Rtools).

Could you please publish the binaries for the latest (3.6.0) version?

---

> ```
> install.packages("mice")
> WARNING: Rtools is required to build R packages but is not currently installed. 
>          Please download and install the appropriate version of Rtools before proceeding:
>   There is a binary version available but the source version is later:
>      binary source needs_compilation
> mice  3.5.0  3.6.0              TRUE
> 
>   Binaries will be installed
> ```

**Comment by stefvanbuuren** [comment]
These should be available at
https://cran.r-project.org/web/packages/mice/index.html


Van: Jan Pilzer <notifications@github.com>
Beantwoorden - Aan: stefvanbuuren/mice <reply@reply.github.com>
Datum: vrijdag 12 juli 2019 om 01:46
Aan: stefvanbuuren/mice <mice@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [stefvanbuuren/mice] Publish binaries for 3.6.0 (#186)


As a casual R user on Windows, I was unable to update mice to the latest version (without installing Rtools).

Could you please publish the binaries for the latest (3.6.0) version?

________________________________

install.packages("mice")

WARNING: Rtools is required to build R packages but is not currently installed.

         Please download and install the appropriate version of Rtools before proceeding:

  There is a binary version available but the source version is later:

     binary source needs_compilation

mice  3.5.0  3.6.0              TRUE



  Binaries will be installed

**Comment by Hirse** [comment]
I'm still seeing the same issue when updating from within RStudio.

The page you linked to also has the `NeedsCompilation` flag set to `yes`. My guess would be that this flag is the reason R doesn't install 3.6.

**Comment by gerkovink** [comment]
Works fine for me. Binary is now 3.6.0 too. 

All the best, 

Gerko

```r
> install.packages("mice")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/mice_3.6.0.tgz'
Content type 'application/x-gzip' length 1501114 bytes (1.4 MB)
==================================================
downloaded 1.4 MB


The downloaded binary packages are in
	/var/folders/9h/ttk51_v162g76nh8szs8lbzw0000gn/T//RtmpFIL428/downloaded_packages
> library(mice)
Loading required package: lattice

Attaching package: ‘mice’

The following objects are masked from ‘package:base’:

    cbind, rbind

> version()
[1] "mice 3.6.0 2019-07-09 /Library/Frameworks/R.framework/Versions/3.6/Resources/library"
```

**Comment by gerkovink** [comment]
The issue you provide is the standard way in which `CRAN` handles package updates: source packages are available before the binary package is distributed. In the meanwhile, the choice to opt-in for the newer version is offered to those who have `RTools` installed. Thus, if you'd like to install from source, then compilation of non-R code (such as C, C++ or Fortran) is needed, because its compilation is operating system dependent and you need a version of `RTools` on your machine. Otherwise, some patience is needed to have the package pre-compiled into a binary that works for your machine language.

**Comment by Hirse** [comment]
I see. Thanks for the explanation.
