### ISSUE TITLE
Glance does not support multiple responses

### ISSUE THREAD

**Issue by rahgonda** [stefvanbuuren/mice#187]
Stef Ban Buuren,

Over the past year and a half I've been using the pool function to combine beta coefficients from multivariate (multiple responses) models from 10 multiply imputed datasets. However, several months later, I'm now getting "Error: Glance does not support linear models with multiple responses" when running the same code that had previously worked. Has there been any update to the package to discontinue this ability?

Thank you,
Rahul

**Comment by gerkovink** [comment]
Dear Rahul, 

`mice` uses `broom` while pooling since version 3.0. If you have updated `mice`, chances are you come from an earlier `mice` version; which explains why pooling now expects a different behaviour than before.

See #121, #142 and #148 for some more detail.

All the best,

Gerko

**Comment by stefvanbuuren** [comment]
Closing because this has been answered before.

**Comment by rahgonda** [comment]
Thank you!
