### ISSUE TITLE
Question: Error in edit.setup(data, setup, ...) : nothing left to impute

### ISSUE THREAD

**Issue by Moaath87** [stefvanbuuren/mice#192]
Hello,

I am relatively new to R and statistics so please excuse me if the question is primitive:

I have a data set: 

head(subset_missed)
  screened reason_not_join age gender        ethnicity food_security assistance      residence
1        y              NA  45      f            white             y          y Home/Apartment
2        y              NA  30      m african_american             y          y Home/Apartment
3        y              NA  29      m            white             y          y Home/Apartment
4        y              NA  48      f            white             y          y Home/Apartment
5        y              NA  74      m  hispanic/latino             y          n Home/Apartment
6        y              NA  24      f            other             y          y Home/Apartment
            type_insurance cost_of_hospitalization stay_length
1 medicare and/or Medicaid                 9598.75      8 days
2 medicare and/or Medicaid                 1137.32      3 days
3                  private                 4689.27      6 days
4                  private                 4322.08      4 days
5                  private                 7804.47      6 days
6                  private                 5015.88      5 days

I write the following code: 

impute=mice(subset_missed[, 1:7], m=3, seed = 123)  
 iter imp variable   1   1   1   2   1   3   2   1   2   2   2   3   3   1   3   2   3   3   4   1   4   2   4   3   5   1   5   2   5   3 
Warning message: Number of logged events: 4
--
When I print the impute, it only recognizes one of the variables with missing data but not the rest. I used the is.na function to double check if R is recognizing the missing values as NA and it is indeed recognizing them. Can you give me an advice, please.

**Comment by Moaath87** [comment]
I tried it again, it gave me the following: 


## Class: mids
## Number of multiple imputations:  5 
## Imputation methods:
##                     age                  gender               ethnicity 
##                      ""                      ""                      "" 
##           food_security              assistance               residence 
##                      ""                      ""               "polyreg" 
##          type_insurance   discharge_destination cost_of_hospitalization 
##                      ""                      ""                      "" 
##             stay_length 
##                      "" 
## PredictorMatrix:
##               age gender ethnicity food_security assistance residence
## age             0      1         0             0          0         1
## gender          1      0         0             0          0         1
## ethnicity       0      0         0             0          0         0
## food_security   0      0         0             0          0         0
## assistance      0      0         0             0          0         0
## residence       1      1         0             0          0         0
##               type_insurance discharge_destination cost_of_hospitalization
## age                        0                     0                       1
## gender                     0                     0                       1
## ethnicity                  0                     0                       0
## food_security              0                     0                       0
## assistance                 0                     0                       0
## residence                  0                     0                       1
##               stay_length
## age                     1
## gender                  1
## ethnicity               0
## food_security           0
## assistance              0
## residence               1
## Number of logged events:  5 
##   it im dep     meth                   out
## 1  0  0     constant             ethnicity
## 2  0  0     constant         food_security
## 3  0  0     constant            assistance
## 4  0  0     constant        type_insurance
## 5  0  0     constant discharge_destination



Then I tried 

> impute$loggedEvents
  it im dep     meth                   out
1  0  0     constant             ethnicity
2  0  0     constant         food_security
3  0  0     constant            assistance
4  0  0     constant        type_insurance
5  0  0     constant discharge_destination
> 

I am not sure why its not recognizing the other variables. I tried the md.pattern and it looks like it is detecting it

**Comment by gerkovink** [comment]
`mice` does exactly what it needs to do. Some of your variables are constant. This means that they either have the same information, or are only observed when others are missing. This leads to computational problems and, hence, these columns are excluded from imputation.

All the best,

Gerko

**Comment by Moaath87** [comment]
I appreciate your prompt response. It is actually neither, the data is very long and only 36 readings are missed out of 1250 rows and the variable is binary not one option. Thank you for your help and advice.

**Comment by gerkovink** [comment]
With constant it is implied that the observed information between the respective columns is constant. the following system would, e.g. also be constant:

```
NA 1
1   2
2   NA
1   2
```
