### ISSUE TITLE
Conditional imputation for categorical and mixed variables - MICE in R

### ISSUE THREAD

**Issue by Alexia93Sab** [stefvanbuuren/mice#193]
Dear Stef Van Buuren,

I am trying to apply multiple imputation in my dataset. I have a variable that is categorical with 7 categories. I am trying to impute data based only in 5 specific categories and not all of them.  I tried to do it with post processing but it doesn't work.  My question is how should we proceed to treat conditional categorical variables?

Another problem that I have is that I have a mixed type Age variable that has some values as integers and some as ranges. I can easily make integers as ranges but I don't want that. If possible I would like to have everything as integers. I thought that I could impute them based on the range they belong. Any suggestions about that?

Thank you in advance :)

**Comment by stefvanbuuren** [comment]
There are no pre-built solutions for these - very data specific - problems. 

I think that you can handle both problems by writing your own `mice.impute.myimpute()` functions, which gives you complete freedom over the imputation process.

**Comment by Alexia93Sab** [comment]
Thank you you very much for your prompt answer. I tried to use something similar with your paper
post["chl"] <- "imp[[j]][,i] <- squeeze(imp[[j]][,i],c(100,300))" and instead of (100, 300) to put the categories that I want. But it doesn't work.

I also tried to use it for multiple ranges but it takes only the first one that I write.

So, in case that I want to add another range to chl (lets say 301-500) do you have any suggestions of how to do it?

Many thanks

**Comment by stefvanbuuren** [comment]
Search the literature for something like "imputation bracketed response", and define your own `mice.impute.xxx()`.
