### ISSUE TITLE
Error in edit.setup(data, setup, ...) : nothing left to impute

### ISSUE THREAD

**Issue by TomasJohansson** [stefvanbuuren/mice#194]
```{r}
library(mice)
# Two data frames (with the only difference being the first x value):
df1 <- data.frame(x = c(1.3, 2, 3, NA, 5) , y = c(100, NA, 300, 400, 500) )
df2 <- data.frame(x = c(1.2, 2, 3, NA, 5) , y = c(100, NA, 300, 400, 500) )
imp1 <- mice(df1) # OK i.e. no error message
imp2 <- mice(df2) # "Error in edit.setup(data, setup, ...) : nothing left to impute"
```

If there is a good reason for this difference in the above results, maybe the error message could 
be more descriptive to make it more obvious what the problem is?

```{r}
---------------------------------------------------------
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mice_3.6.0      lattice_0.20-38

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2        magrittr_1.5      splines_3.6.1     MASS_7.3-51.4    
 [5] tidyselect_0.2.5  R6_2.4.0          rlang_0.4.0       jomo_2.6-9       
 [9] minqa_1.2.4       dplyr_0.8.3       parallel_3.6.1    nnet_7.3-12      
[13] grid_3.6.1        mitml_0.3-7       broom_0.5.2       nlme_3.1-140     
[17] pan_1.6           survival_2.44-1.1 lme4_1.1-21       assertthat_0.2.1 
[21] tibble_2.1.3      crayon_1.3.4      Matrix_1.2-17     nloptr_1.2.1     
[25] purrr_0.3.2       tidyr_0.8.3       rpart_4.1-15      glue_1.3.1       
[29] compiler_3.6.1    pillar_1.4.2      generics_0.0.2    backports_1.1.4  
[33] boot_1.3-22       pkgconfig_2.0.2  
```

**Comment by stefvanbuuren** [comment]
Thanks. Indeed a little terse. 

I changed the error message in mice 3.6.2. You will now get

```r
imp2 <- mice(df2)
Error in edit.setup(data, setup, ...) : 
  `mice` detected constant and/or collinear variables. No predictors were left after their removal.
```

**Comment by stefvanbuuren** [comment]
Related #192

**Comment by squalo78** [comment]
But I do not understand. It does not make sense that with 'df1' there is no error while with 'df2' it gives an error. Only difference is one element which goes from 1.3 to 1.2.

Why the function would detect ` constant and/or collinear variables' in the second case, but not the first case?

**Comment by stefvanbuuren** [comment]
For `df1` the correlation is `0.998906`, for `df2`it is `0.999539`. The latter exceeds the default threshold used by `mice:::find.collinear()`. 

If you don't like the selection step, you can change the default by the `...` argument `threshold = 1.0` of `mice()`. However, `mice:::find.collinear()` is there for a reason, so don't be surprised if that causes issues further down the line.

**Comment by a-a-k** [comment]
what should I do if I need to input to the collinear column? is there any workaround? somehow, my dataframe has NAs only in one column, and it's collinear.

**Comment by stefvanbuuren** [comment]
If you have a collinear column in your data, take it out before imputing.

**Comment by a-a-k** [comment]
> take it out before imputing.

but I need to input directly into _that collinear column_, that's the dilemma I can't figure out, please read my question carefully

**Comment by stefvanbuuren** [comment]
One approach is to apply impute-then-transform to calculate the omitted variable(s) after imputation.

For an example, see <https://stefvanbuuren.name/fimd/sec-knowledge.html#sec:ratio>. Would that solve your problem?
