### ISSUE TITLE
pool anova objects

### ISSUE THREAD

**Issue by KZARCA** [stefvanbuuren/mice#195]
Dear Stef,
I'm trying to understand how to pool mira objects so as to get a pooled ANOVA.  What would be your recommendation for this? To use `anova.mira`, `pool.compare`, `D1`, `D2`, `D3` or something else, maybe a higher level function? I could not find any documentation about it.
Best regards

**Comment by stefvanbuuren** [comment]
Use `D1` if you can. See the discussion in https://stefvanbuuren.name/fimd/sec-multiparameter.html

**Comment by KZARCA** [comment]
That's great! Thank you. Therefore, will pool.compare be deprecated?

**Comment by stefvanbuuren** [comment]
At some point, yes.
