### ISSUE TITLE
remove collinearity false is not working

### ISSUE THREAD

**Issue by Alexia93Sab** [stefvanbuuren/mice#197]
Hi, 

I want to take advantage of collinearity in order to help the algorithm perform better and 
imp(data, remove_collinear = FALSE) is not working. It keeps removing it. 

It is a bug?

Many thanks n advance

**Comment by stefvanbuuren** [comment]
There are two separate switches: `remove.constant` and `remove.collinear` (and its outdated cousin `remove_collinear`). Judging from your example in #196, I assume you'll need `remove.constant`. Note however that doing this leads to a host of warnings further on. 

The default in `mice` is to remove constant and collinear variables before entering the main algorithm. This spares the user from seeing easily preventable warnings.
