### ISSUE TITLE
"non-conformable arrays" error when using method 2l.pmm for cross-classified data

### ISSUE THREAD

**Issue by tetsuyamady** [stefvanbuuren/mice#198]
I get the error message "Error in z0 * u[index_clus, 1:NR, drop = FALSE] : non-conformable arrays" when I try to impute a cross-classified dataset using the method "2l.pmm".

```
dataset <- read.xlsx("dataset.csv")[,-1]
methods <- as.character(read.xlsx("methods.csv")$methods)
predictormatrix <- as.matrix(read.xlsx("predictormatrix.csv")[,-1])
rownames(predictormatrix) <- colnames(predictormatrix)
imp1 <- mice(dataset,m=10,maxit=5,method=methods,predictorMatrix=predictormatrix)
```

I have attached the dataset "dataset.csv", list of methods "methods.csv", and the predictor matrix "predictormatrix.csv". 
"program3" and "locationb" are the grouping variables, and thus I have placed "-2" in those columns.

[dataset.xlsx](https://github.com/stefvanbuuren/mice/files/3764250/dataset.xlsx)

[methods.xlsx](https://github.com/stefvanbuuren/mice/files/3764255/methods.xlsx)

[predictormatrix.xlsx](https://github.com/stefvanbuuren/mice/files/3764256/predictormatrix.xlsx)

I have been able to get the imputation going with either "program3" or "locationb" as the single grouping variable, but not together.
Please let me know what may be wrong with my data or the code.

Thank you.

**Comment by gerkovink** [comment]
The error you receive has to do with calculating the predicted values in function `mice.impute.2l.lmer`, where `2l.pmm` gets its estimates from. 

Since both these functions are not part of `mice`,  I suggest you file a request to the authors responsible for these functions.

See #33
