### ISSUE TITLE
Asking for method = "ppm" gives troubles

### ISSUE THREAD

**Issue by RianneSchouten** [stefvanbuuren/mice#20]
The problem appears to be in the check.method function. The following error is returned when I call for mice(boys, method = "ppm")

Error in check.method(setup, data) : 
  The following functions were not found: mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm

**Comment by stefvanbuuren** [comment]
You probably meant "pmm"? Stef

Verstuurd vanaf mijn iPad

Op 17 nov. 2016 om 20:20 heeft RianneSchouten <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


The problem appears to be in the check.method function. The following error is returned when I call for mice(boys, method = "ppm")

Error in check.method(setup, data) :
The following functions were not found: mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm, mice.impute.ppm

**Comment by RianneSchouten** [comment]
Oef, I'm so sorry! 
At least I now know how these issues work ;) 
But sorry for the trouble. This was very stupid.

**Comment by stefvanbuuren** [comment]
We might stumble and fall, but come out stronger. Keep up the good work!

Van: RianneSchouten <notifications@github.com>
Beantwoorden - Aan: stefvanbuuren/mice <reply@reply.github.com>
Datum: vrijdag 18 november 2016 14:26
Aan: stefvanbuuren/mice <mice@noreply.github.com>
CC: "S. Buuren" <S.vanBuuren@uu.nl>, Comment <comment@noreply.github.com>
Onderwerp: Re: [stefvanbuuren/mice] Asking for method = "ppm" gives troubles (#20)


Oef, I'm so sorry!
At least I now know how these issues work ;)
But sorry for the trouble. This was very stupid.
