### ISSUE TITLE
Plot trace lines for only certain streams and iterations

### ISSUE THREAD

**Issue by markseeto** [stefvanbuuren/mice#200]
Thanks for the mice package. I'm using version 3.6.0.

The documentation for `plot.mids` says that argument `y` is "A formula that specifies which variables, stream and iterations are plotted. If omitted, all streams, variables and iterations are plotted."

How should this formula be specified if we wanted to plot only some of the variables, some of the streams, and some of the iterations?

Example:

```
library(mice)

imp <- mice(nhanes, m = 10, maxit = 10)

# Plot trace lines for hyp and chl only
plot(imp, y = c("hyp", "chl"))

# How do we plot trace lines for hyp and chl only,
# streams 1 to 5, iterations 6 to 10?
```

**Comment by stefvanbuuren** [comment]
Use

```r
plot(imp, y = hyp + chl ~ .it | .ms, subset = .it %in% 6:10 & .m %in% 1:5, layout = c(2,2))
```

Internally, `plot.mids()` uses `.it` for the iterations, `.ms` for the method, `.m` for the streams. As you see above - you can manipulate these from the prompt. Consult the `lattice::xyplot` for argument documentation.
