### ISSUE TITLE
as.mids duplicate row.names error after imputation

### ISSUE THREAD

**Issue by JSYdeJong** [stefvanbuuren/mice#201]
Hi Stef,

I have been struggeling with an error that I get when using the MICE package for an analysis of longitudinal quality of life data. 
I have a dataset with missing values, both due to loss of follow-up and missing cases. I used a quality of life measure for which all data are needed to calculate a score. My dataset is in wide format, so I want to impute the data using MICE, and store the imputed data in "long" format, then calculate quality of life scores and then convert to long-long format (so the imputed datasets in long but also the individual datasets in long format).
After this, I want to convert the data back to a mids object using as.mids, but MICE throws me the error that there are duplicate rownames. What I do not understand is why this is a problem, as longformat databases should have duplicate rownames. Even when asigning new rownames to every row using: row.names(dataset), it still produces the same error. 

Is it possible to convert to long-long format or should I start trying something else? 
Thank you in advance!

Kind regards,
Jelle de Jong

**Comment by stefvanbuuren** [comment]
Did you try to deleting all rownames?
