### ISSUE TITLE
Why don't the results of mice vignette 2 match?

### ISSUE THREAD

**Issue by regiso** [stefvanbuuren/mice#205]
### Here is the vignette code

set.seed(123)
imp <- mice(nhances, m=3, print = F)
imp$pred

### Notice that the age variable has no na's, yet it shows imputation in row 1.
![micevignette2](https://user-images.githubusercontent.com/16366682/69184174-58fbb900-0ae2-11ea-8348-a143b7159cb0.png)
![mymice](https://user-images.githubusercontent.com/16366682/69184175-58fbb900-0ae2-11ea-81ad-f08ca569219b.png)

**Comment by stefvanbuuren** [comment]
Thanks. These differences reflect the fact the `mice` is under active development. 

Later versions do not attempt to re-edit the `predictorMatrix` when the variable is complete. This change doesn't affect the imputation model, so you can safely ignore this difference in setup.

**Comment by gerkovink** [comment]
Vignettes are now in line with `mice 3.6.0`. 

All the best, 

Gerko
