### ISSUE TITLE
pool() requires more than coef() and vcov() methods

### ISSUE THREAD

**Issue by mikeguggis** [stefvanbuuren/mice#207]
The ?mira page and https://www.jstatsoft.org/article/view/v045i03 say that pooling requires coef() and vcov() methods. This appears to not be sufficient. 

Reproducible example...

lm2 <- function(...){
  out = lm(...)
  out$vcov = vcov(out)
  class(out) = "lm2"
  return(out)
}

vcov.lm2 <- function(object){
  object$vcov
}

coef.lm2 <- function(object){
  object$coefficients
}

is.element("coef.lm2",methods(coef))

is.element("vcov.lm2",methods(vcov))

library(mice)

dmice = mice(nhanes, maxit=2,m=2)

fit <- with(dmice, lm2(bmi ~ age))

temp = pool(fit)

The last line results in "Error: No glance method for objects of class lm2"

**Comment by stefvanbuuren** [comment]
Mike, thanks. I have updated the `mira` documentation. 

Related: #106, #142, #190, #187, #148
