### ISSUE TITLE
Glance does not support linear models with multiple responses

### ISSUE THREAD

**Issue by bauerbw** [stefvanbuuren/mice#210]
Hello,

I'm trying to perform multivariate regression with imputed data but keep receiving the following error code: "Glance does not support linear models with multiple responses." 

#impute data
imp = mice(dataset, m = 10)
#create model
fit=with(data = dataset, exp = lm(cbind(dv1, dv2, dv3)~iv1+iv2+iv3))
#summary
summary(pool(fit))

Thanks,
B

**Comment by stefvanbuuren** [comment]
It is easy to do the same by fitting three models, one for each outcome.
