### ISSUE TITLE
Add S3 method for complete.mids to improve integration with tidyverse

### ISSUE THREAD

**Issue by msberends** [stefvanbuuren/mice#212]
Since the `tidyr` package also contains the `complete()` function, I would suggest to add an S3 method for `complete.mids` so it wouldn't make a difference if `tidyr` is loaded after `mice`.

Something like (not tested myself):

```r
#' @exportMethod complete.mids
#' @importFrom tidyr complete
#' @export
#' @noRd
complete.mids <- function (data, action = 1L, include = FALSE, mild = FALSE, ...) {
  mice::complete(data = data, action = action, include = include, mild = mild, ... = ...)
}
```

This could collide with your existing `complete()` function, but that can be solved to define your own `complete.default` and use `UseMethod("complete")` in your current `complete()` function.

Many thanks for your work the last decades! It's awesome!

**Comment by stefvanbuuren** [comment]
Thanks for the suggestion. 

I think your approach will work, but it needs adding the `tidyr` dependency tree to `mice`. I will need to look into the consequences more closely.

**Comment by stefvanbuuren** [comment]
`mice 3.7.5` defines the S3 method `complete.mids()` for the generic `tidyr::complete()`. Name clashes should not occur anymore.

**Comment by stefvanbuuren** [comment]
Related https://stackoverflow.com/questions/40732528/error-in-imputing-data-using-mice-package/60141043#60141043
