### ISSUE TITLE
Imputation for monotone missingness

### ISSUE THREAD

**Issue by squalo78** [stefvanbuuren/mice#213]
When I run the example from the on-line book (https://stefvanbuuren.name/fimd/sec-monotone.html)

data <- nhanes2[, 1:3]

md.pattern(data, plot = FALSE)
   age hyp bmi   
16   1    1    1    0
 1    1    1    0    1
 8    1    0    0    2
       0    8    9   17

imp <- mice(data, visit = "monotone", maxit = 1, m = 2,
            print = FALSE)

and I print 'imp'

> imp
Class: mids
Number of multiple imputations:  2 
Imputation methods:
     age      bmi      hyp 
      ""    "pmm" "logreg" 
PredictorMatrix:
    age bmi hyp
age   0   1   1
bmi   1   0   1
hyp   1   1   0

I would have expected that only 'age' and not 'bmi' would have been used for predicting missing data in 'hyp' (given that we specify the "monotone" option). Am I wrong?

Thanks in advance for any answers.
Giuseppe

**Comment by stefvanbuuren** [comment]
Ah, good question. 

The `monotone` argument only affects the sequence in which variables are imputed. It does not change the `predictorMatrix`. If you want the multivariate monotone method you'll also need to specify the upper triangle of the `predictorMatrix` as zeroes.

I think it is undesirable to do automatic adaptation of the `predictorMatrix`. That could easily lead to sub-optimal solutions in the (typical) case that the missing data pattern is not monotone.
