### ISSUE TITLE
Error in mutate_impl(.data, dots) : Evaluation error: argument "value" is missing, with no default.

### ISSUE THREAD

**Issue by rhandsman** [stefvanbuuren/mice#214]
Hi. I am currently attempting to pool the results of an imputation I ran, but Im running into this error. I am fairly new to coding and am not sure what to do to get rid of this error. 

Error in mutate_impl(.data, dots) : Evaluation error: argument "value" is missing, with no default.

This is my code for the pooling of the imputation: 
`modelFit1 <- with(tempData, lm(wasi_bd_t_pre~scq_total_pre+gec_t_pre))
summary(pool(modelFit1))`

**Comment by stefvanbuuren** [comment]
Is `is.mids(tempData)` equal to `TRUE`?

**Comment by rhandsman** [comment]
Hi! Yes it is.

**Comment by stefvanbuuren** [comment]
OK, would then need a (hopefully small) reproducible example that includes the data and the `mice` function.

**Comment by rhandsman** [comment]
Here is a smaller dataset and code for running the imputation with only a few iterations and imputations. This code is still resulting in that error. Thanks!

[test.xlsx](https://github.com/stefvanbuuren/mice/files/4040513/test.xlsx)

`data.path <- "test.xlsx"
data <- read_excel(path= data.path)

tempData <- mice(data, m=5, maxit = 5)
summary(tempData)

modelFit1 <- with(tempData, lm(wasi_bd_t_pre~Obs_student_total_pre+gec_t_pre))
summary(pool(modelFit1))
`

**Comment by stefvanbuuren** [comment]
I cannot reproduce in `mice 3.7.0`. I get 

```
> summary(pool(modelFit1))
                      estimate std.error statistic  df p.value
(Intercept)             59.087    5.2184     11.32 131  0.0000
Obs_student_total_pre   -1.038    0.5487     -1.89 135  0.0608
gec_t_pre               -0.118    0.0771     -1.53 131  0.1281
```

which seems OK. 

What does `version()` say on your system?

**Comment by rhandsman** [comment]
My version says 3.4.0 should I update the version to the 3.7.0?

**Comment by stefvanbuuren** [comment]
No guarantees, but at least you could give that a try.

**Comment by rhandsman** [comment]
That worked! Thanks!

**Comment by stefvanbuuren** [comment]
Great!
