### ISSUE TITLE
Error when applying polr() using with() to imputed data

### ISSUE THREAD

**Issue by LJEllyson** [stefvanbuuren/mice#215]
Hi,
I'm fairly new to coding and using mice (3.7.0) on a large (900+ observations) data set. I'm trying to conduct an ordinal logistic regression on a variable with 14 levels (which I imputed using the "polr" method) against a multitude (~50) of other numeric and binomial variables. I've gotten as far as trying to use the polr() function from the MASS package with the mice with() function and get the following error. I get the same error regardless of including the argument for Hess= TRUE which I assume is needed when planning to use the summary() function. I tried searching for similar errors but didn't find any that were helpful to this situation. Thanks in advance.

olr <- with(imputed, polr(14_level_factor ~ var 1+var2+var3+varN), Hess= TRUE)

Error in optim(s0, fmin, gmin, method = "BFGS", ...) : 
  initial value in 'vmmin' is not finite
In addition: Warning message:
glm.fit: fitted probabilities numerically 0 or 1 occurred

**Comment by stefvanbuuren** [comment]
Seems that you've got a misplaced bracket.

**Comment by stefvanbuuren** [comment]
No follow-ups, so closing.
