### ISSUE TITLE
predictorMatrix behavior when all entries in a row are zero

### ISSUE THREAD

**Issue by gerjonhannink** [stefvanbuuren/mice#227]
Hi Stef/Gerko,

I have a problem understanding how the `predictorMatrix` works. Stef’s book says “The rows correspond to incomplete target variables, in the sequence as they appear in the data. A value of 1 indicates that the column variable is a predictor to impute the target (row) variable, and a 0 means that it is not used. Thus, in the above example, `bmi` is predicted from `age`, `hyp` and `chl`. Note that the diagonal is 0 since a variable cannot predict itself. Since `age` contains no missing data, `mice()` silently sets all values in the row to 0. The default setting of the `predictorMatrix` specifies that every variable predicts all others.” 

That makes sense, however I cannot explain my results. For example, using the `nhanes` data, let’s say I do not want to impute `hyp` but use `hyp` for the imputation of other variables. 

```
library(mice) # mice version 3.8.0
ini <- mice(nhanes, maxit = 0, print = FALSE, seed = 1)
imp <- mice(nhanes, print = FALSE, seed = 1)
imp$imp$hyp  

# predictormatrix - row ‘hyp’ to 0
pred <- ini$pred
pred["hyp",] <- 0
imp <- mice(nhanes, pred = pred, print = FALSE, seed = 1)
imp$imp$hyp
imp$imp

```

`hyp` should not be imputed but values are all 1. Why is that?

Asking Google for help I also encountered some posts that mentioned to set `method` for `hyp` to `“”`. Is that the case?

```
meth <- ini$method
meth["hyp"] <- ""
imp <- mice(nhanes, pred = pred, method = meth, print = FALSE, seed = 1)
imp$imp$hyp
imp$imp
```
Doing that, obviously `hyp` is not imputed, but I get different imputed values for the other variables.

Can you explain what happens here?

Thanks! 
Gerjon

**Comment by stefvanbuuren** [comment]
Dear Gerjon, thanks for your question. 

If there are no predictors, then `mice` imputes using the intercept only. With just the default number of donors, `pmm` produces the same value for this dataset . If you set `donors = 10`, then you'll see both 1's and 2's.

```
> imp <- mice(nhanes, pred = pred, print = FALSE, seed = 1, donors = 10)
> imp$imp$hyp
   1 2 3 4 5
1  1 1 1 1 1
4  1 2 1 1 1
6  1 1 2 1 1
10 1 1 1 1 1
11 1 1 1 1 2
12 1 1 1 2 1
16 1 2 1 1 1
21 1 2 1 1 1
```

Hope this helps, Stef.

**Comment by gerjonhannink** [comment]
Hi Stef, 
Thanks, that helps! I didn't know `donors` as a `mice` function argument. Guess it defaults to 5?
Gerjon

**Comment by stefvanbuuren** [comment]
Yes, default `donors = 5` for `mice.impute.pmm()`.
