### ISSUE TITLE
Pooled linear mixed model with MICE - unable to obtain confint 

### ISSUE THREAD

**Issue by boniale** [stefvanbuuren/mice#241]
round(summary(pool(imp_modl), conf.int = TRUE), 3)

Error in Math.data.frame(list(term = 1:10, estimate = c(86.511440027337,  : 
  non-numeric variable(s) in data frame: term

Kindly help

**Comment by boniale** [comment]
I have solve the issue. I easily get the confidence interval using this:
 summary(pool(mdbp_imp), conf.int = TRUE,conf.level = 0.95)

Thanks

**Comment by stefvanbuuren** [comment]
OK, looks almost the same to me, but glad that you manage to solve it.
