### ISSUE TITLE
C stack usage 7969332 is too close to the limit

### ISSUE THREAD

**Issue by tingjhenjiang** [stefvanbuuren/mice#242]
Hello,

I build Multidimensional Item Response Theory models from [mirt package](https://cran.r-project.org/web/packages/mirt/mirt.pdf), and then I convert the models to be in a broom::glance() format by using[ datacamp/tidymirt package](https://github.com/datacamp/tidymirt/tree/master/R) and make it a list.
After that I'd like to pool the result using mice::pool. but errors happen. The message is `"C stack usage  7969332 is too close to the limit"`. 
I'd like to know how to solve it.

You can replicate this error by executing following codes:
```
library(mirt)
data <- expand.table(LSAT7)
mod1 <- mirt(data, 1, SE = TRUE)
testmods <- list(mod1,mod1,mod1,mod1,mod1)
testglances <- lapply(testmods, tidymirt:::glance.SingleGroupClass)
mice::pool(testglances)
```
I've tried on a real imputed dataset and build mirt models, but the result is the same.

**Comment by stefvanbuuren** [comment]
`pool()` expects a `mira` object, so be sure to create an object of the appropriate class.

**Comment by tingjhenjiang** [comment]
Hello,
failure is still there after I make it a mira object.
Generating same error(C stack usage 7969332 is too close to the limit) with the following codes:

```
library(mirt)
data <- expand.table(LSAT7)
mod1 <- mirt(data, 1, SE = TRUE)
testmods <- list(mod1,mod1,mod1,mod1,mod1)
testglances <- lapply(testmods, tidymirt:::glance.SingleGroupClass)
testglances <- mice::as.mira(testglances)
mice::pool(testglances)
```

Did I miss something?

```
> testglances$call
mice::as.mira(fitlist = testglances)
> testglances$call1
NULL
> testglances$nmis
NULL
> testglances$analyses
[[1]]
# A tibble: 1 x 12
  nfact nitems ngroups  nest    df converged   AIC  AICc SABIC    HQ   BIC logLik
  <int>  <int>   <int> <int> <dbl> <lgl>     <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
1     1      5       1    10    21 TRUE      5338. 5338. 5355. 5356. 5387. -2659.

[[2]]
# A tibble: 1 x 12
  nfact nitems ngroups  nest    df converged   AIC  AICc SABIC    HQ   BIC logLik
  <int>  <int>   <int> <int> <dbl> <lgl>     <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
1     1      5       1    10    21 TRUE      5338. 5338. 5355. 5356. 5387. -2659.

[[3]]
# A tibble: 1 x 12
  nfact nitems ngroups  nest    df converged   AIC  AICc SABIC    HQ   BIC logLik
  <int>  <int>   <int> <int> <dbl> <lgl>     <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
1     1      5       1    10    21 TRUE      5338. 5338. 5355. 5356. 5387. -2659.

[[4]]
# A tibble: 1 x 12
  nfact nitems ngroups  nest    df converged   AIC  AICc SABIC    HQ   BIC logLik
  <int>  <int>   <int> <int> <dbl> <lgl>     <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
1     1      5       1    10    21 TRUE      5338. 5338. 5355. 5356. 5387. -2659.

[[5]]
# A tibble: 1 x 12
  nfact nitems ngroups  nest    df converged   AIC  AICc SABIC    HQ   BIC logLik
  <int>  <int>   <int> <int> <dbl> <lgl>     <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
1     1      5       1    10    21 TRUE      5338. 5338. 5355. 5356. 5387. -2659.
```

**Comment by stefvanbuuren** [comment]
The `analyses` component should be the fitted models themselves, and not its glanced versions.

**Comment by tingjhenjiang** [comment]
Hello,
failure is still there after I adjust the codes to make `analyses` component to become its original models, but this time the message is `"$ operator not defined for this S4 class"`
Replicating the error with following codes:

```
library(mirt)
library(tidymirt)
library(mice)
data <- expand.table(LSAT7)
mod1 <- mirt(data, 1, SE = TRUE)
testmods <- list(mod1,mod1,mod1,mod1,mod1)
pool(testmods)
```

What should we do if we want to make a model be supported by mice::pool, even though we have made that model be supported in broom::glance format ?

**Comment by stefvanbuuren** [comment]
I do not understand what you're trying to do. All `mod1` models are the same in your example, and there's no point in pooling five identical models.

I get 

```r
> class(mod1)
[1] "SingleGroupClass"
attr(,"package")
[1] "mirt"
> df.residual(mod1)
Error: $ operator not defined for this S4 class
```

This error is not related to `mice`. I suggest you look into `mirt` or `tidymirt`.
