### ISSUE TITLE
mice::pool with broom version 0.7.0 does not support glmerMod anymore

### ISSUE THREAD

**Issue by retogerber** [stefvanbuuren/mice#244]
Hi,
It seems that with the new update of the broom package to version 0.7.0 the pooling of some models (e.g. glmerMod from lme4) does not work anymore. It seems that broom::tidy and broom::glance do not support mixed models anymore. For mixed models the functions broom.mixed::tidy and broom.mixed::glance in the broom.mixed package have to be used instead.
Do you plan to update the mice::pool() function?
Best

**Comment by stefvanbuuren** [comment]
Yes, I plan to update. This took me by surprise.

**Comment by stefvanbuuren** [comment]
Actually, version 3.9.1 already solved the problem, but the fix is not yet on CRAN. For now use workaround

```r
install.packages("devtools")
devtools::install_github(repo = "stefvanbuuren/mice")
```

I expect the CRAN update might take a few days.
