### ISSUE TITLE
How to solve error: Error in chol.default(sym(p$v)) :    the leading minor of order 156 is not positive definite?

### ISSUE THREAD

**Issue by Bigsealion** [stefvanbuuren/mice#252]
data size is 7000*165, method='pmm', most of variables class is num. 
When I use mice ,I get a error.
```
Error in chol.default(sym(p$v)) : 
  the leading minor of order 156 is not positive definite
```
1. I want to know what causes this error and how to solve it?
2. I observed that when mice is running, some variable names will be printed with an '*'(asterisk) after it . I want to know what this means and does it have anything to do with this error?
Thanks!

**Comment by stefvanbuuren** [comment]
See my answer at #250.
