### ISSUE TITLE
Logistic regression model with multiple imputed datasets

### ISSUE THREAD

**Issue by anamgreco** [stefvanbuuren/mice#255]
Hello and thank you, again!

I need to create a new variable to perform a logistic regression model. So far, I have done it like this, but I get the following error:
`# Generate new variable`
`imputed_data$new_variable1<-with(imputed_data,ifelse(imputed_data$x1==0, 0, 1)`
`# Fit logistic regression`
`glm1<-with(imputed, glm(new_variable1~x2+x3+x4, family = binomial(link = "logit")))
	Error in model.frame.default(formula = … : Object is not a matrix`

I managed to do ti like this, but I am not sure if it is equivalent:

`# Convert to long format`
`imputed_long<-mice::complete(imputed_data, action="long",include = TRUE)`
`imputed_long_mids<-as.mids(imputed_long)`
`# Fit logistic regression`
`fitimp1<-with(imputed_long_mids,`
`glm(new_variable1~x2+x3+x4,family = binomial(link = "logit")))` 
`summary(pool(fitimp1),conf.int=TRUE,exponentiate=TRUE),3)`

**Comment by stefvanbuuren** [comment]
See #34 for techniques how to create new variables

See #92 for discussion of pooling after logistic regression.

Perhaps you can find your answers there. If not, make explicit where `mice` doesn't work as intended.

**Comment by anamgreco** [comment]
Thanks again!

Logistic regression is solved, I am still dealing with the creation of the new variable. As in #34 I am trying to do passive imputation but in my case I need to use ifelse() function.Is it possible to do this? If so, how?

I posted the same question in #34, so feel free to ignore or erase this post if you think is better to discuss it there. (I am sorry for duplicating, I am still learning where is the best place to post a question on GitHub).

Thanks a lot again and have a nice weekend!
