### ISSUE TITLE
don't impute censored values

### ISSUE THREAD

**Issue by sdaza** [stefvanbuuren/mice#28]
Hello, 
I am imputing time-varying covariates for a survival analysis. 
I set my data in a wide format.  Is there a way to not impute censored values?

Thanks!

**Comment by stefvanbuuren** [comment]
There is no easy way to do that in mice, since it would lead to missing values in the predictors. What I would do to achieve this is 1) impute all values, and 2) overwrite the censored by NA after imputation. 
Hope this helps, Stef.

**Comment by stefvanbuuren** [comment]
It is now easy to do this. 

The `where` argument introduced in `mice 2.46.0` allows you to specify which cells will be imputed. If you know where the censored cells are, just specify `where` as `FALSE` for those cells, and they will remain `NA`. Missing values in the predictors of imputation models are handled by listwise deletion.

**Comment by sdaza** [comment]
great, thanks!
