### ISSUE TITLE
Pool for cox hazard model

### ISSUE THREAD

**Issue by gajyakichi** [stefvanbuuren/mice#29]
Thank you for great package, mice.

In cox proportional hazard model pooling,
the result showed est was less than zero.

It might be confused with linear regression model.

How is the best method to pool with cox proportional hazard model?

```
library(mice)
library(survival)

#Making database
Tempmice<-mice(imputedmodel,
m=10,maxit=50,meth='pmm', seed=500)

#Cox proportional hazard model
CoxModel.1<- coxph(Tempmice,Surv(FU, Censor==1)~ Factor1+Factor2, method="breslow")

＃Pool
fit<-with(data=Tempmice,CoxModel.1)
coxphimputed<-summary(pool(fit))
coxphimputed
```

**Comment by stefvanbuuren** [comment]
The sequence of statements seems OK to me. The Cox model allows for negative coefficients.
