### ISSUE TITLE
imputing categorical variable in a multilevel model

### ISSUE THREAD

**Issue by sdaza** [stefvanbuuren/mice#33]
Hello, 
I have an individual categorical variable (race) in a panel dataset.  I would like to impute it and use it as a predictor.  I only see the functions:  

mice.impute.2lonly.mean 
mice.impute.2lonly.norm 
mice.impute.2lonly.pmm 

If I use pmm (not sure it is the right thing to do), the imputed values would be used as a continuous variable when imputing other variables. Is that correct? If so, an alternative would be to transform that variable into a factor. 

I get these warnings quite often: 

Warning messages:
1: Some predictor variables are on very different scales: consider rescaling 
2: Some predictor variables are on very different scales: consider rescaling 

Thank you in advance!

**Comment by stefvanbuuren** [comment]
I guess the warning `Some predictor variables are on very different scales: consider rescaling` comes from `lmer()`, and I do not know how to interpret it here.

You may use `mice.impute.2lonly.pmm()` to impute categorical non-varying covariates. It aggregates over the class variable, then imputes, and then expands back to the original classes. If `race` is categorical, then your imputation should also be categorical. If it is a string, then the imputation should be a string. You may check this in your imputed data using the `complete()` function. 

Hope this helps.

**Comment by sdaza** [comment]
Thanks Stef,
When I use `mice.impute.2only.pmm` over a factor, I get an error message. 

```
> ma
          pid sex agei agei2 dghealth clinci frace edui family_id
pid         0   0    0     0        0      0     0    0         0
sex         0   0    0     0        0      0     0    0         0
agei        0   0    0     0        0      0     0    0         0
agei2       0   0    0     0        0      0     0    0         0
dghealth    0   1    1     1        0      1     1    1         0
clinci      0   1    1     1        1      0     1    1         0
frace      -2   1    1     1        1      1     0    1         0
edui        0   1    1     1        1      1     1    0         0
family_id   0   0    0     0        0      0     0    0         0
````

> meth
         pid          sex         agei        agei2     dghealth       clinci 
          ""           ""           ""           ""        "pmm"        "pmm" 
       frace         edui    family_id 
"2lonly.pmm"        "pmm"           "" 
> imp1 <- mice( ex, m = 1 , predictorMatrix = mat ,
+               imputationMethod = meth ,
+               maxit = 5)

 iter imp variable
  1   1  dghealth  clinci  frace
Error in chol.default(sym(v)) : 
  the leading minor of order 1 is not positive definite
In addition: Warning message:
In Ops.factor(0, y) : ‘*’ not meaningful for factors
```

**Comment by stefvanbuuren** [comment]
This is probably caused by linear dependence among the predictors. I see that you have both `agei` and `agei2` in your model. First start both just defining one predictor to impute `frace`, then build onto that.

**Comment by sdaza** [comment]
It looks like the `mice.impute.2lonly.pmm` function has issues dealing with factor variables. The only factor variable with missing data is `frace`. 

```
 iter imp variable
  1   1  dghealth  clinci  frace  edui
  2   1  dghealth  clinci  frace  edui
  3   1  dghealth  clinci  frace  edui
  4   1  dghealth  clinci  frace  edui
  5   1  dghealth  clinci  frace  edui
Warning messages:
1: In Ops.factor(0, y) : ‘*’ not meaningful for factors
2: In Ops.factor(0, y) : ‘*’ not meaningful for factors
3: In Ops.factor(0, y) : ‘*’ not meaningful for factors
4: In Ops.factor(0, y) : ‘*’ not meaningful for factors
5: In Ops.factor(0, y) : ‘*’ not meaningful for factors
```

**Comment by stefvanbuuren** [comment]
Seem that there might be two different issues. For the random intercept model, what do you mean by "it doesn't work"? Still have the `chol.default()` error?

**Comment by sdaza** [comment]
I am adding a reproducible example. The datafile named `ex` is here: https://db.tt/fHD0PjgBkd

```
imp <- mice(ex, maxit = 0)
mat <- imp$predictorMatrix
meth <- imp$meth

# adjust prediction matrix
mat["frace",] <- 0
mat[c("frace", "cedui", "clinci", "dghealth"), "pid"] <- -2

# redefine methods
meth["clinci"] <- "2l.pmm"
meth["cedui"] <- "2l.pmm"
meth["frace"] <- "2lonly.pmm"
meth["dghealth"] <- "2l.pmm"

imp1 <- mice(ex, m = 1 , predictorMatrix = mat ,
              imputationMethod = meth ,
              maxit = 2)

 iter imp variable
  1   1  dghealth  clinci  frace  cedui
  2   1  dghealth  clinci  frace  cedui
Warning messages:
1: In Ops.factor(0, y) : ‘*’ not meaningful for factors
2: In matrix((model.matrix(~cat.columns - 1)[, -1]), ncol = p$categories[p$categories[j,  :
  data length [129038] is not a sub-multiple or multiple of the number of rows [64556]
3: In matrix((model.matrix(~cat.columns - 1)[, -1]), ncol = p$categories[p$categories[j,  :
  data length [129038] is not a sub-multiple or multiple of the number of rows [64556]
4: In Ops.factor(0, y) : ‘*’ not meaningful for factors
5: In matrix((model.matrix(~cat.columns - 1)[, -1]), ncol = p$categories[p$categories[j,  :
  data length [129038] is not a sub-multiple or multiple of the number of rows [64556]


# adding covariates to predict frace
mat["frace", "male"] <- 1
imp2 <- mice(ex, m = 1 , predictorMatrix = mat ,
              imputationMethod = meth ,
              maxit = 2)

 iter imp variable
  1   1  dghealth  clinci  frace
Error in chol.default(sym(v)) : 
  the leading minor of order 1 is not positive definite
In addition: Warning message:
In Ops.factor(0, y) : ‘*’ not meaningful for factors
```

**Comment by stefvanbuuren** [comment]
The function `mice.impute.2l.pmm()` is not part of `mice`, so I suggest you file a request to the authors responsible for these functions. I am willing to take look at `mice.impute.2lonly.pmm()` (which is part of `mice`), so to make it suitable for categorical data, but my time is limited, so I'd prefer to wait until I know that this investment would actually be useful. Stef.

**Comment by sdaza** [comment]
Thanks, Stef. 
If I only use the mice package, I get the same warning message.  So, I guess the issue is related to the `2lonly.pmm``  function. [Here the code.](https://gist.github.com/sdaza/56aef14d725d58e5670c562447f35a84)

**Comment by stefvanbuuren** [comment]
Pushed an extension of `mice.impute.2lonly.pmm()` to factors. Could you give this a try?

**Comment by sdaza** [comment]
Now I get: 

```
Warning messages:
1: In matrix((model.matrix(~cat.columns - 1)[, -1]), ncol = p$categories[p$categories[j,  :
  data length [129038] is not a sub-multiple or multiple of the number of rows [64556]
2: In matrix((model.matrix(~cat.columns - 1)[, -1]), ncol = p$categories[p$categories[j,  :
  data length [129038] is not a sub-multiple or multiple of the number of rows [64556]
3: In matrix((model.matrix(~cat.columns - 1)[, -1]), ncol = p$categories[p$categories[j,  :
  data length [129038] is not a sub-multiple or multiple of the number of rows [64556]
```

**Comment by stefvanbuuren** [comment]
I hunted down the problem. First load `ex.Rdata` and the `mice` 2.37, and now the following will run smoothly.

```
library(mice)

imp <- mice(ex, maxit = 0)
mat <- imp$predictorMatrix
meth <- imp$meth

# adjust prediction matrix
mat[c("frace", "cedui", "clinci", "dghealth"), "pid"] <- -2

# redefine methods
meth["clinci"] <- "pmm"
meth["cedui"] <- "pmm"
meth["frace"] <- "2lonly.pmm"
meth["dghealth"] <- "pmm"

imp1 <- mice(ex, m = 1 , predictorMatrix = mat ,
             imputationMethod = meth ,
             maxit = 2)

cmp <- complete(imp1)
summary(cmp)

```

**Comment by sdaza** [comment]
Thanks! It is working perfectly now. What was the problem?
