### ISSUE TITLE
mice crashes when number of identifiers (id variable) is too big in a long format dataset

### ISSUE THREAD

**Issue by sdaza** [stefvanbuuren/mice#40]
I have a long format dataset with 50,000 individuals and 687174 observations. When the id variable is a factor I get this error: 

```
imp <- mice(ex, maxit = 0)
Error in matrix(rep(predictorMatrix[, j], times = n.dummy), ncol = n.dummy) : 
  long vectors not supported yet: memory.c:1668
```

Is there another way to include the id variable as a fixed predictor?
Thanks!

**Comment by stefvanbuuren** [comment]
`mice` tries to expand your id variable into 50000 dummies, and apparently this is beyond what is currently possible in R. 

I am not sure what you're trying to achieve. There shouldn't be any predictive value in the id variable, so in most scenarios, I would not try to include id as a predictor.

**Comment by sdaza** [comment]
I just wanted to compare the fixed-effects and multilevel imputation.

**Comment by stefvanbuuren** [comment]
OK, 50.000 groups is a bit to much, so either consider using a subset of the data, or try adding the mean outcome per group as a predictor.
