### ISSUE TITLE
Error: 'densityplot' is not an exported object from 'namespace:mice'

### ISSUE THREAD

**Issue by mikgh** [stefvanbuuren/mice#42]
Dear Stef,

As I can see many before me have already said: Thank you very much for providing the community with this indispensable package for R.

I am experiencing an issue, though, with the densityplot-function, which I am unable to resolve:

When calling mice::densityplot or mice::densityplot.mids I get the following error:
`Error: 'densityplot' is not an exported object from 'namespace:mice'`

I have tried updating to the Development version (2.37?) but the problem remains. 

Let me know if you need any more info on this.

Best regards,
Mikkel

**Comment by stefvanbuuren** [comment]
It is properly exported, but the generic function is defined in lattice. Try `library(lattice)`. Will try to find our whether there is a more elegant solution.

**Comment by stefvanbuuren** [comment]
mice 2.40 fixes the integration with the lattice package, so calling

`densityplot(imp)`

and friends should now work.
