### ISSUE TITLE
mice impute missing values? Output of complete always has NAs.

### ISSUE THREAD

**Issue by wolski** [stefvanbuuren/mice#48]
I am trying to impute values using a linear model using mice. My understanding of mice is that it iterates over the rows. For a column with NAs it is using all other columns as predictors, fits the model, and then samples from this model to fill up the NAs.
Here is an example where I generate some data, and than introduce missing data using ampute.

        n <- 100
        xx<-data.frame(x = 1:n + rnorm(n,0,0.1), y =(1:n)*2 + rnorm(n,0,1))
        head(xx)
        res <- (ampute(xx))
        head(res$amp)

The missing data looks like:

                x         y
       1       NA  3.887147
       2 2.157168        NA
       3 2.965164  6.639856
       4 3.848165  8.720441
       5       NA 11.167439
       6       NA 12.835415

Then I am trying to impute the missing data:

       mic <- mice(res$amp,diagnostics = FALSE )
       

And I would expect that then there is non, but there are NA always in one of the columns.

     colSums(is.na(complete(mic,1)))

And in which of the two it is rather random.

By running the code above I am getting:

 
     > colSums(is.na(complete(mic,1)))
      x  y 
      0 30 

but also :

     > colSums(is.na(complete(mic,1)))
      x  y 
     33  0

**Comment by stefvanbuuren** [comment]
Your data are almost collinear 

```
> cor(res$amp, use = "pair")
          x         y
x 1.0000000 0.9998434
y 0.9998434 1.0000000
```

`mice` tries to be smart (and evade some nasty computational problems along the way), and removes nearly collinear variable beforehand. You can see that this happens at `mic$loggedEvents`. 

```
imp$loggedEvents
  it im co dep      meth out
1  0  0  0     collinear   y
```
So this is expected behaviour, but I can also see why you didn't expect it :-)
Stef.

**Comment by stefvanbuuren** [comment]
You may skip removal of collinear variables at initialization by the `remove_collinear` flag.

```r
mic <- mice(res$amp, diagnostics = FALSE , remove_collinear = FALSE)
```
If you do so, `mice` tries to resolve the problem during the iterations. See the large list of complaints in
```
mic$loggedEvents
```
We are working on numerically stabler methods that can handle these difficulties.
