### ISSUE TITLE
Calling mice::mice()

### ISSUE THREAD

**Issue by ochskm** [stefvanbuuren/mice#55]
I want to call mice::mice() from inside my own package. However, even at the command line I run into this problem:
``` r
mice::mice(airquality)
#> Error in check.method(setup, data): The following functions were not found: mice.impute.pmm, mice.impute.pmm
```

I have no problems when doing 
``` r
library(mice)
mice(airquality)
```

Is this a bug or am I missing  something?

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info --------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.3.0 (2016-05-03)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Danish_Denmark.1252         
#>  tz       Europe/Paris                
#>  date     2017-10-02
#> Packages ------------------------------------------------------------------
#>  package   * version date       source        
#>  backports   1.0.4   2016-10-24 CRAN (R 3.3.2)
#>  devtools    1.11.1  2016-04-21 CRAN (R 3.3.0)
#>  digest      0.6.9   2016-01-08 CRAN (R 3.3.0)
#>  evaluate    0.10    2016-10-11 CRAN (R 3.3.0)
#>  htmltools   0.3.5   2016-03-21 CRAN (R 3.3.0)
#>  knitr       1.15.1  2016-11-22 CRAN (R 3.3.0)
#>  lattice     0.20-33 2015-07-14 CRAN (R 3.3.0)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.3.0)
#>  MASS        7.3-45  2016-04-21 CRAN (R 3.3.0)
#>  Matrix      1.2-6   2016-05-02 CRAN (R 3.3.0)
#>  memoise     1.0.0   2016-01-29 CRAN (R 3.3.0)
#>  mice        2.30    2017-02-18 CRAN (R 3.3.3)
#>  nnet        7.3-12  2016-02-02 CRAN (R 3.3.0)
#>  Rcpp        0.12.12 2017-07-15 CRAN (R 3.3.3)
#>  rmarkdown   1.3     2016-12-21 CRAN (R 3.3.0)
#>  rpart       4.1-10  2015-06-29 CRAN (R 3.3.0)
#>  rprojroot   1.2     2017-01-16 CRAN (R 3.3.2)
#>  stringi     1.0-1   2015-10-22 CRAN (R 3.3.0)
#>  stringr     1.0.0   2015-04-30 CRAN (R 3.3.0)
#>  survival    2.39-2  2016-04-16 CRAN (R 3.3.0)
#>  withr       1.0.1   2016-02-04 CRAN (R 3.3.0)
#>  yaml        2.1.13  2014-06-12 CRAN (R 3.3.0)
```

</details>

**Comment by stefvanbuuren** [comment]
This is not a bug, but just the way in which R finds objects. `mice` uses `do.call()` to find the `mice.impute.xxx()` functions. In your example, `mice.impute.pmm()` is not on the search list. As far as I know, R cannot find object that are not on the search list.

A quick hack without `library()` is to copy the impute function to `.GlobalEnv`

```
mice.impute.pmm <- mice::mice.impute.pmm
mice::mice(airquality)
```

Hope this helps.

**Comment by stefvanbuuren** [comment]
To call `mice()` from your own package add

```
importFrom(mice, mice)
importFrom(mice, mice.impute.pmm)
```

to your `NAMESPACE` file. Simply add more `importFrom()` statements for each imputation function you want to import. Also, add `mice` to the `Imports:` field in `DESCRIPTION`.

**Comment by ochskm** [comment]
Ok, thanks for clarifying!

**Comment by DiogoFerrari** [comment]
Unfortunately, that does not work for me. I had to load the whole package to use from my package.

**Comment by NikKrieger** [comment]
It's bad practice to have your package load something into the global environment, and the other proposed solution doesn't work.

**Comment by NikKrieger** [comment]
Just to flesh out my comment a bit more:

I affirm DiegoFerrari's comment:

> Unfortunately, that does not work for me. I had to load the whole package to use from my package.

The code: 
`importFrom(mice, mice)
importFrom(mice, mice.impute.pmm)`
does not solve the problem.

The error occurs in the `mice:::check.method()` function, namely the line:

`notFound <- !vapply(fullNames, exists, logical(1), mode = "function", inherits = TRUE)`

So when it comes down to it, the `exists()` function isn't finding `mice.impute.pmm` where it needs to find it. Understanding exactly how `exists()` works is a little bit over my head.

**Comment by stefvanbuuren** [comment]
I just tried in a fresh session: 

```r
imp <- mice::mice(mice::nhanes)
mice::complete(imp, 2)
```

**Comment by stefvanbuuren** [comment]
In version `mice 3.3.3` I have removed the test that checks for the existence of imputation functions. If the user specifies an imputation whose name cannot be found, then we will see 

```{r}
mice(nhanes, method = "arghh")

   iter imp variable
    1   1Error in get(fn) : object 'mice.impute.arghh' not found
```

which is less elegant than the previous stopping message. 

However, the advantage is that `mice` can now be imported into other packages by just importing the `mice` function. Standard imputation functions need not be imported on an individual basis, since `get()` will find them if they are loaded, but not attached. If `mice` is imported, then they will be loaded, but will not be on the search list. Still `get()` can find them.

I will add a small demo repository that demonstrates the hidden power of `get()`.
