### ISSUE TITLE
cran installation has non 0 exit status

### ISSUE THREAD

**Issue by DJJ88** [stefvanbuuren/mice#56]
Hello,
I tried to installl mice from cran and got the error message below.
Many thanks for the package, the github version works fine.
Best regards,

* installing *source* package ‘mice’ ...
** package ‘mice’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/local/lib/R/include -DNDEBUG  -I"/home/djj/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++  -I/usr/local/lib/R/include -DNDEBUG  -I"/home/djj/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -g -O2  -c match.cpp -o match.o
g++ -shared -L/usr/local/lib -o mice.so RcppExports.o match.o Welcome to R! Goodbye!
g++: error: Welcome: No such file or directory
g++: error: to: No such file or directory
g++: error: R!: No such file or directory
g++: error: Goodbye!: No such file or directory
/usr/local/lib/R/share/make/shlib.mk:6: recipe for target 'mice.so' failed
make: *** [mice.so] Error 1
ERROR: compilation failed for package ‘mice’
* removing ‘/home/djj/R/x86_64-pc-linux-gnu-library/3.4/mice’

The downloaded source packages are in
	‘/tmp/Rtmpgam70t/downloaded_packages’
Warning message:
In install.packages("mice") :
  installation of package ‘mice’ had non-zero exit status

**Comment by stefvanbuuren** [comment]
I used 

```
# install OS-specific version
install.packages("mice")

# install tar.gz source
devtools::install_cran("mice")
```

Both worked fine on my system. 

Perhaps you need to install the development tools for your system? See [https://github.com/hadley/devtools](https://github.com/hadley/devtools) on that.

**Comment by DJJ88** [comment]
Thanks for the reply. Yes, there was no issue with the mice. package

**Comment by cap0** [comment]
I have the same issue with Microsoft Open R version 4.0.2. 
It seems the welcome message is executed as linux commands. 
It is NOT working with install.packages and also with devtools.
I'm on an centos 8

**Comment by gerkovink** [comment]
@cap I cannot replicate this on `R 4.1.2` on UNIX, so it is reasonable to assume that your issue is not related to `mice`.

**Comment by stefvanbuuren** [comment]
Is this related to #445? Try updating `withr`.
