### ISSUE TITLE
Using mice package with Oracle R Enterprise (ORE)

### ISSUE THREAD

**Issue by AkthemRehab** [stefvanbuuren/mice#57]
I have my data in Oracle 12c. I installed the mice package on the ORE server side and tried to use it with the ore frame, but I receive the following error when on trying the md.pattern command:

Error in as.vector(x, mode) : invalid argument 'mode'

When I pull the data to R, and run the same command it works just fine. Please advice whether mice is capable of working with ORE and if so, will appreciate helping to overcoming the above error.

**Comment by stefvanbuuren** [comment]
Thanks for your note. 

I have no experience with Oracle, so I am afraid I cannot be of much help. The data that you enter into `mice()`, is that an R `data.frame`? If not, could you convert to a `data.frame`?

**Comment by AkthemRehab** [comment]
Theoretically, it is possible to convert it to data.frame. But I have memory constraints and want to use a SQL database in order not to load all the data into memory. If you have mice package working with any SQL database other than Oracle, please let me know.

Thanks for your reply.

**Comment by stefvanbuuren** [comment]
Perhaps you need something like http://db.rstudio.com. The following `mice` workflow is a bit crude, but it should work with `dplyr` and `tidyverse`.

```{r}
## dplyr workflow using multiple imputation by mice
library("mice")
library("dplyr")
library("purrr")
my_seed <- 123
z2 <- nhanes %>%
   mice(seed = my_seed, print = FALSE) %>%
   mice::complete("long") %>%
   split(.$`.imp`) %>%
   map(~lm(chl ~ bmi + hyp + age, data = .)) %>%
   as.mira() %>% 
   pool() %>%
   summary()
z2
```
Hope this is enough to get you started.
