### ISSUE TITLE
Min(y) not meaningful for factors error in pool.compare

### ISSUE THREAD

**Issue by thomasklausch2** [stefvanbuuren/mice#60]
I am writing with a short bug report on mice’s `pool.compare` function. I did not have the time to understand the details of the problem but it goes as follows.

When pooling logistic regression models using ‘likelihood’ of `pool.compare`, the function returns an error when the dependent variable in the glm was a factor instead of a numeric (0,1) variable. The problem occurs because `min(y)` is used at some point in the function which is not defined for factors. 

Based on one of the examples from `pool.compare`, a code to replicate the problem is:

```
imp2  <- mice(boys, maxit=2)
fit0 <- with(imp2, glm( as.factor(gen>levels(gen)[1]) ~ hgt+hc,family=binomial))
fit1 <- with(imp2, glm( as.factor(gen>levels(gen)[1]) ~ hgt+hc+reg,family=binomial))
pool.compare(fit1, fit0, method='likelihood', data=imp2)
```

I hope this helps to improve the code.

Best regards,
Thomas

**Comment by stefvanbuuren** [comment]
Thomas, thanks. Resolved this in `mice 2.46.7`.
