### ISSUE TITLE
Issues with mice.impute.2l.norm to impute multilevel missing data

### ISSUE THREAD

**Issue by huque15** [stefvanbuuren/mice#62]
#The following error appears when I tried to impute using mice.impute.2l.norm

"x + diag(diag(x) * ridge) : non-conformable arrays"

I find that the similar codes work for mice.impute.2l.pan.

Here is the debug code from R studio:

![mice debug](https://user-images.githubusercontent.com/6721233/34805511-9d7ef52c-f6d2-11e7-941a-10e0ced32cdf.jpg)

Looking more closely to the problem. It appears that 
line 117 of the code resulted in a matrix of element 1. Can you please confirm.

Please find the attached dataFCS2 and codes to reproduce the problem

ini2<-mice(dataFCS2,maxit=0)
pred<-ini2$predictorMatrix
pred[,c("ID","wave","sep2")]<-0
pred["bmiz",]<-c(-2,1,1,1,0,2,1,0,1,0)
pred["famStruc",]<-c(-2,1,1,1,0,1,1,0,0,1)
meth2<-ini2$method
meth2[c("bmiz","famStruc")]<-"2l.norm"
imp2<-mice(dataFCS2,m=40,meth=meth2,pred=pred)

**Comment by stefvanbuuren** [comment]
Thanks for reporting. I couldn't locate the dataFCS2 data set, so cannot yet reproduce.

**Comment by huque15** [comment]
Thanks for your quick response. Please find the attached file.
[dataFCS2.xlsx](https://github.com/stefvanbuuren/mice/files/1624425/dataFCS2.xlsx)

**Comment by stefvanbuuren** [comment]
huque15, this is actually a bug in mice.impute.2l.norm(), which is actually noted in the documentation:

`Added June 25, 2012: The currently implemented algorithm does not handle predictors that are specified as fixed effects (type=1). When using mice.impute.2l.norm(), the current advice is to specify all predictors as random effects (type=2).

When you change the 1's in the `predictorMatrix` to 2's, it will run.  

Obviously, it would be better to solve this in the code.

**Comment by stefvanbuuren** [comment]
Not quite sure, but this is probably solved by #119

**Comment by gerkovink** [comment]
Indeed solved now
