### ISSUE TITLE
Predictive mean matching for non-numerical data?

### ISSUE THREAD

**Issue by acnb** [stefvanbuuren/mice#63]
I try to use mice::mice.impute.pmm for imputation, but get an error when the data is not numerical. Here is an example:

    xname <- c('age', 'hgt', 'wgt', 'reg')
    r <- stats::complete.cases(boys[, xname])
    x <- boys[r, xname]
    y <- boys[r, 'tv']
    ry <- !is.na(y)
    yimp <- mice.impute.pmm(y, ry, x) # Error
    yimp2 <- mice.impute.sample(y, ry, x) # works 

I believe pmm worked as I intended before an update but I am not 100% sure. I am now using  mice version 2.46.0.

Thanks for looking into this issue,

Andreas

**Comment by stefvanbuuren** [comment]
Normally we wouldn't call `mice.impute.pmm()` directly. The problem here is that `reg` is a factor, while `mice.impute.pmm()` expects that `x` is a `model.matrix` not a `data.frame`. When you call `mice(...)` the proper expansion is done for you.
