### ISSUE TITLE
fastpmm

### ISSUE THREAD

**Issue by lnonell** [stefvanbuuren/mice#70]
Hi
I can't find fastpmm as mice.impute method, is the Rcpp version for pmm no longer available?

cheers

Lara

**Comment by gerkovink** [comment]
Hi Lara,

`fastpmm` is now the default `pmm` method in mice and can be called by `mice.impute.pmm`. The old (slower) `mice.impute.pmm` code was deprecated and has now been fully replaced with `fastpmm`. 

All the best,

Gerko

**Comment by lnonell** [comment]
Great, many thanks,
Lara
