### ISSUE TITLE
Function `md.pattern` does not work with character variables

### ISSUE THREAD

**Issue by steffenWagner** [stefvanbuuren/mice#71]
Hi Stef,

thanks for creating the mice package. Great work, great documentation!

When working with mice using `md.pattern` to inspect my data, I run into a problem which is due to `character` columns in my data. Here is a stand alone xample based on the `iris` data set:

First everything is fine and as expected:
```r
# load package
library(mice)

# Load iris data to Global Env.
data(iris)

# Generate missing Values
iris$Species[1:5] <- NA
iris$Sepal.Length[4:10] <- NA
head(iris, n = 11)


# Use `md.pattern` to inspect missing data
md.pattern(iris)  # everything is fine and as expected
```

Problems arise when the factor variable `Species` is transformed into `character`:

```r
# Convert factor variable to character
iris$Species <- as.character(iris$Species)
table(iris$Species, useNA = "a")  # missing are still there
md.pattern(iris)  # generates misleading output with non-informative warning
```

The unwanted behavior regarding `character` variables is due to the `x <- data.matrix(x)` in line 57 of https://github.com/stefvanbuuren/mice/blob/master/R/md.pattern.r. `data.matrix` converts according its documentation all values into `numeric` which of course is not meaningful for characters but works for factors.

Therefore I would like to suggest that `md.pattern` either produces an warning when ``character` variables are used in the input data.frame and converts them automatically into factors using for example the following code:

```r
# Suggestion for line 56 in md.pattern.r
if (is.data.frame(x)) {
  if(any(sapply(x), is.character)){
    x[sapply(x, is.character)] <- lapply(x[sapply(x, is.character)], factor)
    warning('Columns of class `character` transformed into `factor`')
  }
  x <- data.matrix(x)
}
```

Thanks in advance!

For the sake of completeness:
```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mice_2.46.0     lattice_0.20-35

loaded via a namespace (and not attached):
 [1] MASS_7.3-48     compiler_3.4.3  Matrix_1.2-12   tools_3.4.3     survival_2.41-3 nnet_7.3-12     yaml_2.1.14     Rcpp_0.12.12   
 [9] rpart_4.1-12    splines_3.4.3   grid_3.4.3    
```

**Comment by steffenWagner** [comment]
I had another thought about dealing with non-numeric columns in `md.pattern`. To make it bullet-proof, the suggested enhancement to `md.pattern` should better look like this:

```r
# Suggestion for line 56 in md.pattern.r
if (is.data.frame(x)) {
  if(!all(sapply(x, is.numeric))){
    x[!sapply(x, is.numeric)] <- lapply(x[!sapply(x, is.numeric)], factor)
    warning('Columns of class `character` transformed into `factor`')
  }
  x <- data.matrix(x)
}
```
By selecting the non-numeric columns and converting them to factors, not only character columns as in my first suggestion will be treated.

**Comment by gerkovink** [comment]
Hi steffenWagner,

From a data science perspective, you raise a valid point. I have merged your suggestions into pull request #74 in such a way that setting argument `convert.char = TRUE` would execute your code suggestion. The reason for this 'switch' is that data streams that are truly of class `character` may severely impact the number of missing data patterns. In most such scenarios, neither imputing or modelling the character information would be informative from a missing data perspective. 

Thanks again. 

All the best, 

Gerko

**Comment by steffenWagner** [comment]
Hi Gerko,

thanks for considering the improvement. I agree that the additional argument is the best way to steer the conversion by the user herself. 

In addition I would suggest a `warning` as soon as `convert.char=FALSE` and the existence of `character`columns in the data, to make the user become aware of the potential problem. Something like would do the job:

```
if(!convert.char && !all(vapply(x, is.numeric, logical(1)))){
  warning('`x` contains columns of type `character`. Please consider setting `convert.char = TRUE`.')
}
```

I am just mentioning this, because it took me quite some time to **notice** the unplausible amount of `NA` values I got from `md.pattern` due to `character` elements in my data set. 

Furthermore I guess, this problem will become more relevant since more and more people work with `tidyverse` functions in data preparation where the former default `stringsAsFactors = TRUE` doesn´t hold anymore.

Best,
Steffen

**Comment by gerkovink** [comment]
Hi Steffen, 

The function is ow much more robust and provides informative warnings about the nature of its behaviour and proposes suggestions to improve interpretation by the user. See the latest commits in #74. Thanks for your input. 

All the best, 

Gerko

**Comment by steffenWagner** [comment]
Hi Gerko,

thanks a lot for your work regarding the great mice package. With `mice` it starts to make fun dealing with missing values which are in general a nuisance!

Best,
Steffen
