### ISSUE TITLE
pool.compare with ordered logistic

### ISSUE THREAD

**Issue by aseemmahajan** [stefvanbuuren/mice#77]
Hi,

I'm conducting a likelihood ratio test with two ordinal logistic regressions using pool.compare(), but encounter the error that "model matrix %*% coefs" has non-conformable arguments. 

Looking at the function pool.compare, I think this occurs because the coefficients outnumber the columns of the model.matrix, since polr() with J ordinal levels produces J-1 intercepts (i.e, J-2 more than the model matrix).

This produces an error in the Llogistic function, which tries to multiply the (n x k) model matrix by the (k -J - 2) coefficients.

Apologies if I'm just applying this incorrectly, but I couldn't find much more guidance online.

Thanks

**Comment by aseemmahajan** [comment]
I'm not sure if it's useful, but I went ahead and wrote a function that produces the log-likelihood from the imputed dataset. Substituting this into the pool.compare function when we have an ordinal regression should allow it to work I think.

````
LLloglik2 <- function(form, data, coef.vec){
	logistic <- function(mu) exp(mu)/(1 + exp(mu))
	y <- model.frame(form, data)[, 1]
	lev.y <- levels(y)
	nl <- length(lev.y)
	main.vars <- coef.vec[c(1:(length(coef.vec) - (nl - 1)))]
	intercept <- coef.vec[is.element(coef.vec, main.vars) == FALSE]
	Xb <- model.matrix(form, data)[, -1] %*% main.vars
	ll.df <- data.frame(matrix(NA, nrow = length(y), ncol = nl)) 
	names(ll.df) <- lev.y
	# First variable
	ll.df[, 1] <- logistic(-Xb + intercept[1])
	for(jj in 2:(nl-1)){
	# Mid variables
		ll.df[ , jj] <- logistic(-Xb + intercept[jj]) - rowSums(ll.df[, c(1:jj-1)]) 
	}
	# Last variable
	ll.df[, nl] <- 1 - rowSums(ll.df[, -nl])

	likelihood <- rowSums(ll.df * model.matrix( ~ 0 + y))
	loglikelihood <- sum(log(likelihood))
        return(loglikelihood)}
````

**Comment by stefvanbuuren** [comment]
Aseemmahajan, would the Wald test be a solution to your problem? Stef.

**Comment by aseemmahajan** [comment]
Thanks! I was relying on an ordinal loglinear model so I ended up using my own likelihood test function which I ended up modeling based on pool.compare(). I think I posted it but happy to send along the most recent version of it if it’s worth incorporating.

________________________________

**Comment by stefvanbuuren** [comment]
Thanks. I'll pass on for now. The `dev` version of `mice` has a new function called `D3()`, which takes the deviances directly from fitted object, thus eliminating the need to calculate the likelihood by hand. I assume that would also work for your model, so perhaps you might give that a try...
