### ISSUE TITLE
multinom MaxNWts argument in polyreg and polr methods

### ISSUE THREAD

**Issue by alegen** [stefvanbuuren/mice#8]
The functions [mice.impute.polyreg](https://github.com/stefvanbuuren/mice/blob/master/R/mice.impute.polyreg.r#L81) and [mice.impute.polr](https://github.com/stefvanbuuren/mice/blob/master/R/mice.impute.polr.r#L75) attempt to set the MaxNWts argument of the multinom call (which is passed further to nnet), but there is a type. The argument in the source code is maxNWts (lower M), but the nnet library uses MaxNWts (ref. on page 4 of [nnet.pdf](http://cran.r-project.org/web/packages/nnet/nnet.pdf)).

**Comment by alegen** [comment]
I am attaching a [link to a pull request][1] I submitted that fixes this bug.

[1]: https://github.com/stefvanbuuren/mice/pull/9

**Comment by stefvanbuuren** [comment]
Thanks. Now fixed.
