### ISSUE TITLE
Enhance reporting tools for glm.mids objects?

### ISSUE THREAD

**Issue by aomidpanah** [stefvanbuuren/mice#81]
Hi all,

Forgive me if this is not the right forum to voice a suggestion. I am new to Github, but an avid useR, moderately familiar with the mice package, and less so multiple imputation in general.

I am interested in extending the S3 object system to improve reporting and programming of multiply imputed GLM analyses. Some S3 methods which I find are useful are: `confint` and `anova`. An example of such an implementation, simply using the output from summary, is:

```
## a confidence interval method for multiply imputed, pooled GLMs
confint.mipo <- function(object, parm, level=0.95, ...) {
  x <- summary(object)
  if (missing(parm))
    parm <- rownames(x)
  b <- x[parm, 'est', drop=F]
  s <- x[parm, 'se']
  lims <- c((1-level)/2, 1-(1-level)/2)
  sweep(x = s %o% qnorm(lims), STATS = b, MARGIN = 1, FUN = '+')
}
```

**Comment by stefvanbuuren** [comment]
Adam, thanks for your suggestion. There is standard functionality in `mice 2.46.0 `for obtaining the 95% confidence interval. The `dev` branch has a function `summary.mipo()` that allows setting the level of the confidence interval. I assume these will also work for your type of analysis.
