### ISSUE TITLE
cbind.mids command

### ISSUE THREAD

**Issue by Synnoove** [stefvanbuuren/mice#86]
Hi,

I´m very new at imputation in R, and the commands cbind.mids and rbind.mids do not seem to be working. I get the commands cbind.data.frame, CBind and cbind2, but not cbind.minds. Is this because I have an older version of MICE? Or is it something I´m doing wrong?
This is the command I use:

library(mice)
cbind.mids(imp, add_weight)

and this is the error-message I get:
Error in cbind.mids(imp, add_weight) : 
  could not find function "cbind.mids"

Best regards,
Synnøve

**Comment by gerkovink** [comment]
Hi Synnøve, 

The function `cbind.mids` and `rbind.mids` are not exported from the `mice` namespace. Still you can access it by specifically addressing the namespace as per the following example:

`library(mice)`
`#impute the nhanes data with defaults`
`imp <- mice(nhanes)` 
`#add a matrix with 25 rows and 2 columns`
`imp2 <- mice:::cbind.mids(imp, matrix(1:50, 25,2)) `
`#ask for the completed data`
`complete(imp2)`

May I ask how you came across this function?

All the best, 

Gerko

**Comment by stefvanbuuren** [comment]
Just using `cbind()`, `rbind()` or `ibind()` should do the job. No need to use the (old) `cbind.mids` and friends.
