### ISSUE TITLE
Multilevel imputation: categorical/non-normal distributed variables

### ISSUE THREAD

**Issue by bgravesteijn** [stefvanbuuren/mice#87]
Dear professor van Buuren,

Is it possible to extend the mice package to a version where a function for first level imputation of categorical and non-normal distributed variables is possible? Since this is only available for normal distributed variables using 2l.pan, 2l.norm and 2l.lmer. 

Thank you very much in advance,

Greetings,

Benjamin Gravesteijn

**Comment by stefvanbuuren** [comment]
There's a lot these days. Check out https://stefvanbuuren.name/fimd/sec-multi-intro.html

**Comment by bgravesteijn** [comment]
Thank you for the info! That's going to be helpful!
