### ISSUE TITLE
"Empty" imputation in mice

### ISSUE THREAD

**Issue by alexanderrobitzsch** [stefvanbuuren/mice#90]
Hi Stef,

I ran

```
library(mice)
data(nhanes)
imp <- mice::mice(nhanes, m=0, maxit=0)
```

and obtained the error message `invalid 'dimnames' given for data frame`.

Is this intended? I suppose that the problem becomes visible since `mice 3.0.0`.

Alexander

**Comment by stefvanbuuren** [comment]
Good catch. `mice(nhanes, m = 0)` actually didn't work either in `mice 2.46.0`, so this baby appears to have flown under the radar for many years. Will repair with a more informative error message.

**Comment by stefvanbuuren** [comment]
`mice 3.0.1` now stops on `m = 0` with error message.
