### ISSUE TITLE
Pooled logistic regression with MICE - unable to obtain confint

### ISSUE THREAD

**Issue by mccallad** [stefvanbuuren/mice#92]
Hi there

I have been using MICE to generate imputed datasets for pooled logistic regression. I am trying to output odds ratio and 95% confidence intervals. The example code below was working until yesterday when I updated my packages. Unfortunately, re-installation did not fix the issue and I am not sure where I am going wrong.

`require(mice)
set.seed(123)

nhanes$hyp <- as.factor(nhanes$hyp) #Hypertension as factor

#Can run logistic regression on (non-imputed) dataset
model <- glm(hyp ~ bmi, family=binomial(link='logit'), nhanes)
model_or <- exp(cbind(OR= coef(model), confint(model))) #Output with odds ratio and 95% CI

#Using the nhanes dataset as an example
imputed_data <- mice::mice(nhanes, m=25, method="pmm", maxit=10, seed=12345)
imputed_model <- with(imputed_data, glm(hyp ~ bmi, family=binomial(link='logit')))
imputed_model_summary <- (summary(pool(imputed_model)))
imputed_model_OR <- exp(cbind(imputed_model_summary[,“est”],imputed_model_summary[,“lo 95”],imputed_model_summary[,“hi 95”])) #exponentiate the coefficient and the lower and upper 95% CI
imputed_model_summary <- (cbind(imputed_model_OR,imputed_model_summary)) #Combine into a single table

#No longer able outputting 95% CI`

Is there a way of outputting 95% CI from the pooled output? Many thanks for any assistance.

Andrew

**Comment by stefvanbuuren** [comment]
The `summary.mira()` function has changed in `mice 3.0`. The names of the columns now conform to the `broom` package. You can now request the estimates directly in the linear or exponentiate scale, as follows 

```
require(mice, warn.conflicts = FALSE)
packageVersion("mice")
set.seed(123)
nhanes$hyp <- as.factor(nhanes$hyp)

# Can run logistic regression on (non-imputed) dataset
model <- glm(hyp ~ bmi, family = binomial(link = 'logit'), nhanes)
model_or <- exp(cbind(OR = coef(model), confint(model)))

# Using the nhanes dataset as an example
imputed_data <- mice::mice(nhanes, m = 25, method = "pmm", 
                           maxit = 10, seed = 12345, print = FALSE)
imputed_model <- with(imputed_data, 
                      glm(hyp ~ bmi, family = binomial(link = 'logit')))

# linear scale
round(summary(pool(imputed_model), conf.int = TRUE), 3)

# log odds scale
round(summary(pool(imputed_model), conf.int = TRUE, exponentiate = TRUE), 3)
```

**Comment by mccallad** [comment]
That's hugely helpful - thank you for the very quick reply!

**Comment by jaminday** [comment]
Using mice v3.3.0, when running the above example code (posted on 31 May 2018), I get the following warning when pooling on the log odds scale using `round(summary(pool(imputed_model), conf.int = TRUE, exponentiate = TRUE), 3)`:

    Warning message:
    In process_mipo(z, object, conf.int = conf.int, conf.level = conf.level,  : 
        Exponentiating coefficients, but model did not use a log or logit link function

This is despite computing the `imputed_model` object with `family = binomial(link = 'logit'))` as in the example code.

Is it safe to ignore this message, as know the model was computed using a logit link function?

**Comment by zoryfl** [comment]
I am experiencing a very similar issue as @jaminday - any update on this?

I am calling the function as follows:
imp_long %>%
 by(as.factor(.$.imp), glm, formula=k2, family=binomial(link="logit")) %>%
  pool() %>% 
   summary(conf.int=T, exponentiate=T)

Warning message is the same as above.

**Comment by stefvanbuuren** [comment]
The warning comes from an inappropriate test of the `mipo` object, which does not preserve the model settings. The warning can be ignored. It is actually superfluous, and therefore removed in `mice 3.4.2`.

**Comment by missingKobe** [comment]
> The `summary.mira()` function has changed in `mice 3.0`. The names of the columns now conform to the `broom` package. You can request the estimates directly in the linear or log odds scale, as follows
> 
> ```
> require(mice, warn.conflicts = FALSE)
> packageVersion("mice")
> set.seed(123)
> nhanes$hyp <- as.factor(nhanes$hyp)
> 
> # Can run logistic regression on (non-imputed) dataset
> model <- glm(hyp ~ bmi, family = binomial(link = 'logit'), nhanes)
> model_or <- exp(cbind(OR = coef(model), confint(model)))
> 
> # Using the nhanes dataset as an example
> imputed_data <- mice::mice(nhanes, m = 25, method = "pmm", 
>                            maxit = 10, seed = 12345, print = FALSE)
> imputed_model <- with(imputed_data, 
>                       glm(hyp ~ bmi, family = binomial(link = 'logit')))
> 
> # linear scale
> round(summary(pool(imputed_model), conf.int = TRUE), 3)
> 
> # log odds scale
> round(summary(pool(imputed_model), conf.int = TRUE, exponentiate = TRUE), 3)
> ```



> Using mice v3.3.0, when running the above example code I get the following warning when pooling on the log odds scale using `round(summary(pool(imputed_model), conf.int = TRUE, exponentiate = TRUE), 3)`:

Using mice v3.15.0, when running the above example code I get the following warning when pooling on the log odds scale using round(summary(pool(imputed_model), conf.int = TRUE, exponentiate = TRUE), 3):
      Warning message: Error in Math.data.frame(list(term = 1:35, estimate = c(0.46500606968507,  : 
  non-numeric-alike variable(s) in data frame: term.
 I do not know why, This question has been bothering me for a long time, I hope you can reply.

**Comment by gerkovink** [comment]
The column 'term' from the summary output is categorical, so the warning indicates that the desired process in rounding makes no sense there.

**Comment by missingKobe** [comment]
Very thanks! That's hugely helpful ! I have also two questions to ask: 
1. I have been using MICE to generate imputed datasets, Is it possible to stratify this imputed datasets according to gender and then perform logistic regression. If so how can I stratify this  imputed datasets?
2.  I have been using MICE to generate imputed datasets,  Is it possible to run BKMR package analysis (or WQS analysis)using this  imputed datasets?
 Many thanks for any assistance.

**Comment by missingKobe** [comment]
Very thanks!&nbsp;Very helpful to me!
&nbsp;


**consider**
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gerko ***@***.***&gt;; 
发送时间: 2023年4月16日(星期天) 凌晨1:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [amices/mice] Pooled logistic regression with MICE - unable to obtain confint (#92)





 
The column 'term' from the summary output is categorical, so the warning indicates that the desired process in rounding makes no sense there.

**Comment by BhavanaK-94** [comment]
I'm also getting the same warning message with the code below.
using round(summary(pool(imputed_model), conf.int = TRUE, exponentiate = TRUE), 3):

Warning message: Error in Math.data.frame(list(term = 1:35, estimate = c(0.46500606968507, :
non-numeric-alike variable(s) in data frame: term.

I understand that the term is categorical so, I'm getting an error message. Is there any way that I can include the term variable and use the above code to get OR and 95% CI?

**Comment by gerkovink** [comment]
There is an easy fix: converting the `term` column to row names avoids the situation that `base::round()` objects against the non-numeric column completely, such as with function `tibble::column_to_rownames()`. The following codeblock implements this:

``` r
library(mice, warn.conflicts = FALSE)
library(tibble)
set.seed(123)
nhanes$hyp <- as.factor(nhanes$hyp)

# Using the nhanes dataset as an example
imputed_data <- mice::mice(nhanes, m = 25, method = "pmm", 
                           maxit = 10, seed = 12345, print = FALSE)
imputed_model <- with(imputed_data, 
                      glm(hyp ~ bmi, family = binomial(link = 'logit')))

# linear scale
imputed_model |>
  pool() |>
  summary(conf.int = TRUE) |>
  tibble::column_to_rownames("term") |>
  round(3)
#>             estimate std.error statistic     df p.value  2.5 % 97.5 %
#> (Intercept)   -1.443     3.873    -0.372 14.618   0.715 -9.716  6.831
#> bmi            0.007     0.143     0.050 14.890   0.961 -0.298  0.313
```

<sup>Created on 2023-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
